### ISSUE TITLE
Unable to install Service fabric runtime

### ISSUE THREAD

**Issue by githubkelv** [microsoft/service-fabric#1021]
Service Fabric Runtime Version: 7.1.456

Environment: Local development pc

Trying to install the local cluster for development and testing.
1. Installed visual studio 2019 community (latest)
2. Enable Service Fabric Tools.
3. Dotnet core sdk 3.1.401
4.  Dotnet core runtime 2.1 , 2.2, 3.1

Description: 
04/09/2020 11:28:43 PM,Info,Installing Service Fabric Runtime. Logs written to C:\WINDOWS\TEMP\InstallFabricRuntime_637348877232650781.log
04/09/2020 11:28:43 PM,Info,Running extract in parallel.
04/09/2020 11:28:43 PM,Info,Unpackaging autoextractor...
04/09/2020 11:28:43 PM,Info,Removing temporary directory C:\Program Files\Microsoft Service Fabric.4hfe4hnc.ixu
04/09/2020 11:28:43 PM,Info,05/09/2020 7:28:43 AM Running Process: powershell.exe -NoProfile Get-ExecutionPolicy -Scope CurrentUser with timeout 00:01:00
04/09/2020 11:28:43 PM,Error,Exception type: System.ComponentModel.Win32Exception, Message: The system cannot find the file specified, Stack:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.ServiceFabric.InstallFabricRuntime.Utility.ExecuteCommand(String command, String arguments, TimeSpan timeout)
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program.TrySetPowershellExecutionPolicy()
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program.Main(String[] args)
Press enter to exit. Process will automatically close after 30 seconds.
04/09/2020 11:28:44 PM,Info,Creating temporary runtime directory C:\Program Files\Microsoft Service Fabric.ufayjsb5.mvn.
04/09/2020 11:28:44 PM,Info,Extracting runtime cab to C:\Program Files\Microsoft Service Fabric.ufayjsb5.mvn...
04/09/2020 11:28:44 PM,Info,05/09/2020 7:28:44 AM Running Process: C:\WINDOWS\TEMP\MicrosoftServiceFabricAutoextractor.exe /L "C:\Program Files\Microsoft Service Fabric.ufayjsb5.mvn" /E /Y with timeout 01:00:00
04/09/2020 11:28:53 PM,Info,Successfully extracted cab file to C:\Program Files\Microsoft Service Fabric.ufayjsb5.mvn

Tried on a 2nd laptop with the exact same steps and i'm able to install it.

**Comment by githubkelv** [comment]
Resolved it by adding
%SystemRoot%\system32  to PATH env variable
