### ISSUE TITLE
Where is FabricDeployer.dll source code?

### ISSUE THREAD

**Issue by drnic** [Microsoft/service-fabric#103]
I went to submit PR to fix `cannont`, and try to figure out what the error meant, but it turns out its not in this repo. None of this stack trace for the `dotnet $DIR/FabricDeployer.dll` application seems to be in this repo. Where is this code coming from? Somewhere on github or internal MS libraries?

```
Setting environment for FabricDeployer to run
Running FabricDeployer on /var/vcap/jobs/azure-service-fabric/config/ClusterManifest.xml
System.Fabric.FabricDeployer.ClusterManifestValidationException: Cluster manifest validation failed with exception System.ArgumentException: Section Management parameter ImageStoreConnectionString cannont be rooted in a drive for multi machine deployments
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.WriteError(String format, Object[] args)
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.ValidateImageStore(Boolean isSingleMachineDeployment)
   at System.Fabric.Management.WindowsFabricValidator.FabricValidator.Validate()
   at System.Fabric.FabricDeployer.FabricValidatorWrapper.ValidateAndEnsureDefaultImageStore()
   at System.Fabric.FabricDeployer.FabricValidatorWrapper.ValidateAndEnsureDefaultImageStore()
   at System.Fabric.FabricDeployer.UpdateNodeStateOperation.OnExecuteOperation(DeploymentParameters parameters, ClusterManifestType clusterManifest, Infrastructure infrastructure)
   at System.Fabric.FabricDeployer.CreateorUpdateOperation.OnExecuteOperation(DeploymentParameters parameters, ClusterManifestType clusterManifest, Infrastructure infrastructure)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disableFileTrace)
   at System.Fabric.FabricDeployer.Program.Main(String[] args)
```

**Comment by drnic** [comment]
Oh no, I found `WinFab.CoreCLR.Libs/Fabric.Code/FabricDeployer.dll` in the v0.1.tgz/`externals` folder, but no src code in there.

**Comment by bpm-ms** [comment]
Unfortunately right now the managed/C# code doesn't build on linux so we had to bring it in prebuilt.  This is really frustrating and this is one of the highest priority fixes/improvements as part of our transition to open source.  @anmolah or @hrushib may be able to give an update on the timeline/how far along we are in getting this code out.
