### ISSUE TITLE
Currently, the ExpectedClusterSize is 7 while the node count is 5.

### ISSUE THREAD

**Issue by Ruveles** [microsoft/service-fabric#1069]
Service Fabric Runtime Version: 7.1.409.9590
Environment: Standalone 
OS(Windows/Linux): Windows

Description: 

Hello!
After unsuccessfully deleting and adding nodes, I am unable to update the cluster configuration.
But now, after running this command:

Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath .\ClusterConfig.json

I get this errors in EventViewer:
1. 
In cluster manifest/infrastructure manifest, the value of ExpectedClusterSize must be smaller than the number of nodes. Currently, the ExpectedClusterSize is 7 while the node count is 5.
2.
Cluster manifest validation failed with exception System.Fabric.FabricDeployer.ClusterManifestValidationException: Cluster manifest validation failed with exception System.ArgumentException: In cluster manifest/infrastructure manifest, the value of ExpectedClusterSize must be smaller than the number of nodes. Currently, the ExpectedClusterSize is 7 while the node count is 5.
   at System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility.WriteErrorAndThrow(String format, Object[] args)
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.VerifyExpectedClusterSize()
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.ValidateSettings()
   at System.Fabric.Management.WindowsFabricValidator.FabricValidator.Validate()
   at System.Fabric.FabricDeployer.FabricValidatorWrapper.ValidateAndEnsureDefaultImageStore()
   at System.Fabric.FabricDeployer.FabricValidatorWrapper.ValidateAndEnsureDefaultImageStore()
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disableFileTrace)
   at System.Fabric.Management.ImageBuilder.FabricProvisionOperation.ProvisionFabric(String localCodePath, String localConfigPath, String configurationCsvFilePath, String infrastructureManifestFilePath, Boolean validateOnly, TimeSpan timeout). ClusterManifestPath: C:\ProgramData\SF\srv-orch31\Fabric\work\IB\132483058541261257\caoc1orl.2my

In this case, the real number of nodes in the cluster is 8.

At first there were 8. Then I had to remove 3 and add them again.
I added 3 nodes with the commands like this:

Add-ServiceFabricNode -NodeName "srv-aos31" -NodeType "InteractiveOnlyAOSNodeType" -IpAddressOrFQDN "srv-aos31.adm.local" -UpgradeDomain "ud0" -FaultDomain "fd:/fd0" -FabricRuntimePackagePath "C:\Temp\WindowsFabric.7.1.409.9590.cab"

Orchestrators this data store in the cache. Although the real ones are different from them.
I've tried a lot of things, nothing helps.
Somewhere it stores values that are not updated.

I have only one idea left - to rebuild the entire cluster again.

Has anyone come across a similar question?

**Comment by maburlik** [comment]
We've made some changes in 7.2, which is released today, to manage node count issues for standalone clusters. Do you see the latest set of nodes when you query the current cluster configuration? If so, and if after upgrading to 7.2 you are still hitting the same issues, take a backup of the cluster configuration, induce data loss for UpgradeOrchestrationService, and restore the state by re-applying the same cluster configuration via an upgrade.

New-Item -Path C:\temp -ItemType Directory -Force
$uid=[System.Guid]::NewGuid().Guid
$configpath="C:\temp\ClusterConfig.json"

Get-ServiceFabricClusterConfiguration > $configpath
Start-serviceFabricPartitionDataLoss -OperationId $uid -DataLossMode FullDataLoss -PartitionId 00000000-0000-0000-0000-000000006000 -ServiceName "fabric:/System/UpgradeOrchestrationService"

# Ensure data loss operation is completed
Get-ServiceFabricPartitionDataLossProgress -OperationId $uid

# restore state
Start-ServiceFabricClusterConfigurationUpgrade  -ClusterConfigPath $configpath

**Comment by craftyhouse** [comment]
@Ruveles 
Please let us know if you still hit this on 7.2 and we can re-open.
