### ISSUE TITLE
Moving from 6.1.467 to 6.2.262 gives exception when using Service Remoting V2

### ISSUE THREAD

**Issue by ComponentFactory** [Microsoft/service-fabric#108]
I use the V2 of service remoting for communication between my stateless services. I have implemented custom serialization by deriving from the IServiceRemotingMessageSerializationProvider interface and providing an instance of this to the FabricTransportServiceRemotingListener class. My custom serializer is very simple and is just the DataContractSerializer but where I provide it with a set of known types. This allows me to define a service interface with methods that take a base class but when called at runtme I can provide a range of derived classes. The known types allow it to work without throwing an exception because it does not know about the derived classes.

This all works fine in 6.1.467. Today I upgraded all the packages to the latest versions and now it crashes when creating the FabricTransportServiceRemotingListener instances. It has the following error...

`TypeLoadException: Could not load type 'System.Fabric.Common.Tracing.TableEntityKind' from assembly 'System.Fabric, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.`

It seems to be related to using the 6.2.262 version of the service fabric. I have ensured that all the projects are upgraded to the same latest version. Here is the full exception if it helps...

`System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'System.Fabric.Common.AppTrace' threw an exception.
  Source=Microsoft.ServiceFabric.Internal
  StackTrace:
   at System.Fabric.Common.AppTrace.get_TraceSource()
   at Microsoft.ServiceFabric.FabricTransport.Runtime.FabricTransportListenerSettings.TryLoadFrom(String sectionName, FabricTransportListenerSettings& listenerSettings, String configPackageName)
   at Microsoft.ServiceFabric.FabricTransport.Runtime.FabricTransportListenerSettings.GetDefault(String sectionName)
   at Microsoft.ServiceFabric.Services.Remoting.FabricTransport.Runtime.FabricTransportRemotingListenerSettings.GetDefault(String sectionName)
   at Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Runtime.FabricTransportServiceRemotingListener.InitializeSerializersManager(IServiceRemotingMessageSerializationProvider serializationProvider, FabricTransportRemotingListenerSettings listenerSettings)
   at Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Runtime.FabricTransportServiceRemotingListener..ctor(ServiceContext serviceContext, IService serviceImplementation, FabricTransportRemotingListenerSettings remotingListenerSettings, IServiceRemotingMessageSerializationProvider serializationProvider)
   at Insight.Backend.Shared.All.AutomaticStatelessService.<CreateServiceInstanceListeners>b__63_0(StatelessServiceContext c) in D:\Insight\Cluster\Insight.Backend.Shared.All\StatelessService\AutomaticStatelessService.cs:line 381
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.<OpenCommunicationListenersAsync>d__19.MoveNext()

Inner Exception 1:
TypeInitializationException: The type initializer for 'ExtensionsEvents' threw an exception.

Inner Exception 2:
TypeLoadException: Could not load type 'System.Fabric.Common.Tracing.TableEntityKind' from assembly 'System.Fabric, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.`

**Comment by ashishnegi** [comment]
@ComponentFactory What is the runtime version you are using ? It seems that you have upgrade the apps to 6.2.262 but your SF Cluster runtime is 6.1.467.

**Comment by ashishnegi** [comment]
SF Cluster runtime version should always be higher than SF SDK version of apps deployed in cluster.

**Comment by ComponentFactory** [comment]
Bother, your right. The cluster is still on 6.1.467 and my code is on the later version. Thanks.
