### ISSUE TITLE
Configure Windows security using gMSA - cluster creation fails

### ISSUE THREAD

**Issue by mcurko** [microsoft/service-fabric#1084]
Service Fabric Runtime Version: 7.2.434.9590

Environment: Standalone

Description: Installation of a cluster attempted, sequence of actions (Azure VNET with a AD DC and a domain-joined VM, same subnet):

I have created a AD group "cluster", containing a VM "clustervm1".

Created a service account:

```
Add-KdsRootKey –EffectiveTime ((get-date).addhours(-10))  
New-ADServiceAccount -Name "sfcluster$" -DNSHostName "sfcluster.mons.hr" -ServicePrincipalNames "http/servicefabric/sfcluster.mons.hr" -PrincipalsAllowedToRetrieveManagedPassword cluster
Get-ADServiceAccount sfcluster$ -Properties * | FL DNSHostName,KerberosEncryptionType,ManagedPasswordIntervalInDays,Name,PrincipalsAllowedToRetrieveManagedPassword,SamAccountName
```

Added the service account to the domain-joined VM "clustervm1":

```
Add-WindowsFeature RSAT-AD-PowerShell
Install-AdServiceAccount sfcluster$
Test-AdServiceAccount sfcluster$
```

Used the following in the config file:

```
"ClustergMSAIdentity": "sfcluster@mons.hr",
"ClusterSPN": "http/servicefabric/sfcluster.mons.hr",
"ClientIdentities": [
	{
		"Identity": "mons.hr\\mcurko",
		"IsAdmin": true
	}
]
```

When run as a local admin, the script results in:

```
Error,3520,FabricDeployer.FabricDeployer,System.Fabric.FabricDeployer.ClusterManifestValidationException: Cluster manifest validation failed with exception System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException: Current security context is not associated with an Active Directory domain or forest.
	   at System.DirectoryServices.ActiveDirectory.DirectoryContext.GetLoggedOnDomain()
```
	   
OK, maybe I should be logged in as the domain admin, so let's try again:

```
Error,4956,FabricDeployer.FabricDeployer,System.Fabric.FabricDeployer.ClusterManifestValidationException: Cluster manifest validation failed with exception System.DirectoryServices.ActiveDirectory.ActiveDirectoryServerDownException: The server is not operational.
	Name: "mons.hr"
	 ---> System.Runtime.InteropServices.COMException: The server is not operational.
```
	 
Hm, what server is not operational? VM clustervm1 and DC are in the same Azure VNET subnet, so no network problems. Turned off the firewall on the DC, same thing. Restarted the DC, againg the same. Changed all the references to "mons.hr" in the config to something else, same thing (so it's probably not a problem in the config). I wonder why does it mention the domain name for "server is not operational"?

If I change nodes.ipaddress from localhost to FQDN, sometimes the installer fails with messages like:

`Cluster manifest validation failed with exception System.ArgumentException: Invalid RunAs section: parameter account name sfcluster.mons.hr is invalid`

Using IP address instead of FQDN doesn't help.

Thw whole trace is:

```
System.Fabric.FabricDeployer.ClusterManifestValidationException: Cluster manifest validation failed with exception System.DirectoryServices.ActiveDirectory.ActiveDirectoryServerDownException: The server is not operational.

Name: "mons.hr"
 ---> System.Runtime.InteropServices.COMException: The server is not operational.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.PropertyValueCollection.PopulateList()
   at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
   at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
   at System.DirectoryServices.ActiveDirectory.PropertyManager.GetPropertyValue(DirectoryContext context, DirectoryEntry directoryEntry, String propertyName)
   --- End of inner exception stack trace ---
   at System.DirectoryServices.ActiveDirectory.PropertyManager.GetPropertyValue(DirectoryContext context, DirectoryEntry directoryEntry, String propertyName)
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at System.Fabric.Management.WindowsFabricValidator.SecuritySettingsValidator.VerifyClusterSpn(Dictionary`2 securitySection)
   at System.Fabric.Management.WindowsFabricValidator.SecuritySettingsValidator.VerifySecuritySettings_WindowsIdentityCredentials(CredentialType clusterCredentialType, CredentialType serverCredentialType, Dictionary`2 clusterManifestSecuritySection)
   at System.Fabric.Management.WindowsFabricValidator.SecuritySettingsValidator.VerifyAuthenticationSettings()
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.ValidateSettings()
   at System.Fabric.Management.WindowsFabricValidator.FabricValidator.Validate()
   at System.Fabric.FabricDeployer.FabricValidatorWrapper.ValidateAndEnsureDefaultImageStore()
   at System.Fabric.FabricDeployer.FabricValidatorWrapper.ValidateAndEnsureDefaultImageStore()
   at System.Fabric.FabricDeployer.ConfigureOperation.OnExecuteOperation(DeploymentParameters parameters, ClusterManifestType clusterManifest, Infrastructure infrastructure)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disableFileTrace)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.NewNodeConfigurationInner(String clusterManifestPath, String infrastructureManifestPath, String jsonClusterConfigPath, String fabricDataRoot, String fabricLogRoot, String fabricHostCredentialUser, SecureString fabricHostCredentialPassword, Boolean runFabricHostServiceAsManual, Boolean removeExistingConfiguration, FabricPackageType fabricPackageType, String fabricPackageRoot, String machineName, String fabricRuntimeCabPath, Boolean fabricIsPreInstalled)
System.Fabric.FabricDeployer.ClusterManifestValidationException: Cluster manifest validation failed with exception System.DirectoryServices.ActiveDirectory.ActiveDirectoryServerDownException: The server is not operational.
```

And now the funny part: if I add the DC IP in the hosts file like this:

`10.10.0.4 mons.hr`

the installation succeeds...
[files.zip](https://github.com/microsoft/service-fabric/files/5573035/files.zip)

Observed behavior: error

Expected Behavior: success

OS(Windows/Linux): Windows

If this is a regression, which version did it regress from? n/a

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
Same root cause as https://github.com/microsoft/service-fabric/issues/1082
