### ISSUE TITLE
Installation of Azure Serice Fabric SDK fails

### ISSUE THREAD

**Issue by fgrueninger** [microsoft/service-fabric#1093]
## Expected Behavior
Successful installation of Microsoft Azure Serice Fabric SDK - 4.2.434.

## Current Behavior
Installation of Microsoft Azure Serice Fabric SDK - 4.2.434 fails.

## Steps to Reproduce
1. Started MicrosoftAzure-ServiceFabric-CoreSDK.exe
2. Entered my local admin account
3. Clicked install
4. "We're sorry. The following pproducts have failed to install."

## Context (Environment)
Windows 10 x64 19042.630

#### Service Fabric Runtime and SDK Version :
4.2.434

#### Operating System :
Windows 10 x64 19042.630

I tried installing Microsoft Azure Serice Fabric SDK - 4.2.434 using MicrosoftAzure-ServiceFabric-CoreSDK.exe.

My user doesn't have admin rights, but I entered the credentials of a local admin. I'm the only logged in user, and I never had the SDK installed.

This is what I get in the log:

```
11/29/2020 6:49:54 PM,Info,Installing Service Fabric Runtime. Logs written to C:\WINDOWS\TEMP\InstallFabricRuntime_637422761946584362.log
11/29/2020 6:49:54 PM,Info,Running extract in parallel.
11/29/2020 6:49:54 PM,Info,Unpackaging autoextractor...
11/29/2020 6:49:54 PM,Info,11/29/2020 7:49:54 PM Running Process: powershell.exe -NoProfile Get-ExecutionPolicy -Scope CurrentUser with timeout 00:01:00
11/29/2020 6:49:55 PM,Info,Current Powershell Execution Policy: RemoteSigned
11/29/2020 6:49:55 PM,Info,Searching for legacy installation registry key.
11/29/2020 6:49:55 PM,Info,Service Fabric Product not detected in registry.
11/29/2020 6:49:55 PM,Info,Creating temporary runtime directory C:\Program Files\Microsoft Service Fabric.xosndgom.si4.
11/29/2020 6:49:55 PM,Info,Extracting runtime cab to C:\Program Files\Microsoft Service Fabric.xosndgom.si4...
11/29/2020 6:49:55 PM,Info,11/29/2020 7:49:55 PM Running Process: C:\WINDOWS\TEMP\MicrosoftServiceFabricAutoextractor.exe /L "C:\Program Files\Microsoft Service Fabric.xosndgom.si4" /E /Y with timeout 01:00:00
11/29/2020 6:50:00 PM,Error,Exception type: System.IO.IOException, Message: The process cannot access the file 'C:\WINDOWS\TEMP\MicrosoftServiceFabricAutoextractor.exe' because it is being used by another process., Stack:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program.TryExtractExe(String fabricExtractPath)
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program.<>c__DisplayClass36_1.<Main>b__3()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program.Main(String[] args)
11/29/2020 6:50:00 PM,Info,Cleaning temporary directory C:\Program Files\Microsoft Service Fabric.xosndgom.si4
Press enter to exit. Process will automatically close after 30 seconds.

```

**Comment by ChrisBurgessMS** [comment]
The error that you are getting acts like the A/V is holding onto the binary and not letting service fabric run it.  I've seen this happen with other A/V programs where they are slow to release access to the binary.  This is not something that we have had reports on so what we recommend for you is to add a couple of A/V exceptions for a short period of time to get through setup.

First would be to add an exception for binaries run from the path %localappdata%\Microsoft\Web Platform Installer\installers   If that doesn't do the trick then add one more exception only for the duration of setup and allow binaries to be executed from %windir%\temp.  Once the SDK has been installed you should go back and remove these exceptions.

**Comment by boydc2014** [comment]
Can you please try Windows Powershell instead of Powershell 7
