### ISSUE TITLE
GetUpgradeProgress incorrect API docs

### ISSUE THREAD

**Issue by hbuckle** [microsoft/service-fabric#1114]
The [GetUpgradeProgress](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-getclusterupgradeprogress) API returns the `ApplicationHealthPolicyMap` property as an object, but according to the API docs it should be an array.
This causes an error in generated clients as seen [here](https://github.com/microsoft/service-fabric-client-dotnet/issues/79)

## Expected Behavior
Get-SFClusterUpgradeProgress / Microsoft.ServiceFabric.Client.Http.ClusterClient.GetClusterUpgradeProgressAsync return succesfully

## Current Behavior
```powershell
Get-SFClusterUpgradeProgress : Failed to deserialize json response from server.
```

```
Exception Info: Microsoft.ServiceFabric.Common.Exceptions.ServiceFabricException: Failed to deserialize json response from server.
  ---> Newtonsoft.Json.JsonReaderException: Unexpected JsonToken StartObject.
    at Microsoft.ServiceFabric.Client.Http.JsonReaderExtensions.ReadStartArray(JsonReader reader)
    at Microsoft.ServiceFabric.Client.Http.JsonReaderExtensions.ReadList[T](JsonReader reader, Func`2 deserializerFunc)
    at Microsoft.ServiceFabric.Client.Http.Serialization.ClusterUpgradeDescriptionObjectConverter.GetFromJsonProperties(JsonReader reader)
    at Microsoft.ServiceFabric.Client.Http.JsonReaderExtensions.Deserialize[T](JsonReader reader, Func`2 getFromJsonPropertiesFunc)
    at Microsoft.ServiceFabric.Client.Http.Serialization.ClusterUpgradeDescriptionObjectConverter.Deserialize(JsonReader reader)
    at Microsoft.ServiceFabric.Client.Http.Serialization.ClusterUpgradeProgressObjectConverter.GetFromJsonProperties(JsonReader reader)
    at Microsoft.ServiceFabric.Client.Http.JsonReaderExtensions.Deserialize[T](JsonReader reader, Func`2 getFromJsonPropertiesFunc)
    at Microsoft.ServiceFabric.Client.Http.Serialization.ClusterUpgradeProgressObjectConverter.Deserialize(JsonReader reader)
    at Microsoft.ServiceFabric.Client.Http.ServiceFabricHttpClient.SendAsyncGetResponse[T](Func`1 requestFunc, String relativeUri, Func`2 deserializeFunc, String requestId, CancellationToken cancellationToken)
    --- End of inner exception stack trace ---
    at Microsoft.ServiceFabric.Client.Http.ServiceFabricHttpClient.SendAsyncGetResponse[T](Func`1 requestFunc, String relativeUri, Func`2 deserializeFunc, String requestId, CancellationToken cancellationToken)
```

This is the raw JSON from the API

```json
{
  "CodeVersion": "6.5.676.9590",
  "ConfigVersion": "2",
  "UpgradeDomains": [
    {
      "Name": "0",
      "State": "Completed"
    },
    {
      "Name": "1",
      "State": "Completed"
    },
    {
      "Name": "2",
      "State": "Completed"
    },
    {
      "Name": "3",
      "State": "Completed"
    },
    {
      "Name": "4",
      "State": "Completed"
    }
  ],
  "UpgradeState": "RollingForwardCompleted",
  "NextUpgradeDomain": "",
  "RollingUpgradeMode": "Monitored",
  "UpgradeDescription": {
    "CodeVersion": "6.5.676.9590",
    "ConfigVersion": "2",
    "UpgradeKind": "Rolling",
    "RollingUpgradeMode": "Monitored",
    "UpgradeReplicaSetCheckTimeoutInSeconds": 4294967295,
    "ForceRestart": false,
    "MonitoringPolicy": {
      "FailureAction": "Rollback",
      "HealthCheckWaitDurationInMilliseconds": "PT0H0M30S",
      "HealthCheckStableDurationInMilliseconds": "PT0H1M0S",
      "HealthCheckRetryTimeoutInMilliseconds": "PT0H45M0S",
      "UpgradeTimeoutInMilliseconds": "PT12H0M0S",
      "UpgradeDomainTimeoutInMilliseconds": "PT2H0M0S"
    },
    "ClusterHealthPolicy": {
      "ConsiderWarningAsError": false,
      "MaxPercentUnhealthyNodes": 100,
      "MaxPercentUnhealthyApplications": 0
    },
    "EnableDeltaHealthEvaluation": true,
    "ClusterUpgradeHealthPolicy": {
      "MaxPercentDeltaUnhealthyNodes": 0,
      "MaxPercentUpgradeDomainDeltaUnhealthyNodes": 0
    },
    "ApplicationHealthPolicyMap": {
      "ApplicationHealthPolicyMap": [
        {
          "Key": "fabric:\/System",
          "Value": {
            "ConsiderWarningAsError": false,
            "MaxPercentUnhealthyDeployedApplications": 0,
            "DefaultServiceTypeHealthPolicy": {
              "MaxPercentUnhealthyServices": 0,
              "MaxPercentUnhealthyPartitionsPerService": 0,
              "MaxPercentUnhealthyReplicasPerPartition": 0
            },
            "ServiceTypeHealthPolicyMap": [
              {
                "Key": "ClusterManagerServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "DnsServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "EventStoreServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "FMServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "FaultAnalysisServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "FileStoreServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "NamingStoreService",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "RepairManagerServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              },
              {
                "Key": "UpgradeServiceType",
                "Value": {
                  "MaxPercentUnhealthyServices": 0,
                  "MaxPercentUnhealthyPartitionsPerService": 0,
                  "MaxPercentUnhealthyReplicasPerPartition": 0
                }
              }
            ]
          }
        }
      ]
    },
    "SortOrder": "Default"
  },
  "UpgradeDurationInMilliseconds": "PT0H18M1.98432S",
  "UpgradeDomainDurationInMilliseconds": "PT0H0M0.0636127S",
  "UnhealthyEvaluations": [],
  "CurrentUpgradeDomainProgress": {
    "DomainName": "",
    "NodeUpgradeProgressList": []
  },
  "StartTimestampUtc": "2019-12-27T14:15:33.886Z",
  "FailureTimestampUtc": "0001-01-01T00:00:00.000Z",
  "FailureReason": "None",
  "UpgradeDomainProgressAtFailure": {
    "DomainName": "",
    "NodeUpgradeProgressList": []
  }
}
```

ApplicationHealthPolicyMap definition
https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/servicefabric/data-plane/Microsoft.ServiceFabric/stable/7.0/servicefabric.json
https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-model-clusterupgradedescriptionobject#applicationhealthpolicymap

```json
    "ApplicationHealthPolicyMap": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ApplicationHealthPolicyMapItem"
      },
```

#### Service Fabric Runtime and SDK Version :
7.0.457.9590
6.5.676.9590

#### Operating System :
Windows

**Comment by craftyhouse** [comment]
@motanv are you able to confirm which refresh this was included in and close? thanks!
