### ISSUE TITLE
Unable to install SF SDK v4.2.457

### ISSUE THREAD

**Issue by rotodd** [microsoft/service-fabric#1163]
**Describe the bug**
I am unable to install the Service Fabric SDK version 4.2.457 when I download the installer [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started).

**Area/Component**:
Installation

**To Reproduce**
1. Go to [this webpage](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started).
2. Click on 'Install the Microsoft Azure Service Fabric SDK'
3. Run the installer

**Expected behavior**
SF is installed

**Observed  behavior**:
Installer shows error, SF is not installed, installer allows for retries.

**Screenshots**
![2021-03-01 10_34_53-Window](https://user-images.githubusercontent.com/54082711/109542490-f8478400-7a79-11eb-9f01-6270af64605d.png)

**Service Fabric Runtime Version:** 
4.2.457

**Environment:**
 - Standalone
 - Windows 10
 - OS build 19042.804
 - Version 20H2

**Additional context**
Logs:

```
3/1/2021 6:34:09 PM,Info,Installing Service Fabric Runtime. Logs written to C:\WINDOWS\TEMP\InstallFabricRuntime_637501916496759144.log
3/1/2021 6:34:09 PM,Info,Running extract in parallel.
3/1/2021 6:34:09 PM,Info,Unpackaging autoextractor...
3/1/2021 6:34:09 PM,Info,3/1/2021 10:34:09 AM Running Process: powershell.exe -NoProfile Get-ExecutionPolicy -Scope CurrentUser with timeout 00:01:00
3/1/2021 6:34:09 PM,Info,Removing temporary directory C:\Program Files\Microsoft Service Fabric.u32ebrh1.zfz
3/1/2021 6:34:09 PM,Error,Exception type: System.ComponentModel.Win32Exception, Message: The system cannot find the file specified, Stack:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.ServiceFabric.InstallFabricRuntime.Utility.ExecuteCommand(String command, String arguments, TimeSpan timeout)
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program.TrySetPowershellExecutionPolicy()
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program.Main(String[] args)
Press enter to exit. Process will automatically close after 30 seconds.
3/1/2021 6:34:10 PM,Info,Creating temporary runtime directory C:\Program Files\Microsoft Service Fabric.wjx3owyx.daf.
3/1/2021 6:34:10 PM,Info,Extracting runtime cab to C:\Program Files\Microsoft Service Fabric.wjx3owyx.daf...
3/1/2021 6:34:10 PM,Info,3/1/2021 10:34:10 AM Running Process: C:\WINDOWS\TEMP\MicrosoftServiceFabricAutoextractor.exe /L "C:\Program Files\Microsoft Service Fabric.wjx3owyx.daf" /E /Y with timeout 01:00:00
3/1/2021 6:34:14 PM,Info,Successfully extracted cab file to C:\Program Files\Microsoft Service Fabric.wjx3owyx.daf

```

What I have tried so far:
- Restarting my device
- Checking my device for updates
- Redownloading the installer
- Checking to ensure a broken version of SF is not already installed
- Rerunning the installer
- Installing the Microsoft Azure Service Fabric SDK instead (same error appears)
- Updated the PATH environment variable (as suggested [here](https://github.com/microsoft/service-fabric/issues/1021#issuecomment-689365852))
---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by rotodd** [comment]
[InstallFabricRuntime.log](https://github.com/microsoft/service-fabric/files/6063860/InstallFabricRuntime.log)

**Comment by rotodd** [comment]
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/54082711/109572570-55efc680-7aa2-11eb-81a9-866d01757024.png)

An update: I was able to get the installer to run by adding these values to my PATH env var
