### ISSUE TITLE
[BUG] -5-node local cluster deployment of stateless API service leads to port bind failure; Code Version 7.2.477.9590

### ISSUE THREAD

**Issue by Monte-Christo** [microsoft/service-fabric#1183]
**Describe the bug**
Deploying a simple .NET Core 3.1 app consisting of a (stateless) Web API and three stateful services via VS 2019 "start debugging" raises errors for a five-node cluster config. One node is successful at binding to the API endpoint, the others fail because the corresponding port is "already in use".

Deployment to a 1-node cluster works just fine.

**Area/Component**:
Reliable Services, stateless service deployment

**To Reproduce**
1. Create a stateless Web API service based on :NET Core 3.1.
2. Deploy to 5-node local dev cluster using the Start button in VS 2019
3. Check status in SF Explorer: App runs at first, but API service soon displays port binding  errors
4. It appears that the API service runs on all five nodes, but only one node can bind to the port the API service uses.

Error message on 4 of the five nodes:
```
'System.RA' reported Warning for property 'ReplicaOpenStatus'.
Replica had multiple failures during open on _Node_3. API call: IStatelessServiceInstance.Open(); Error = System.IO.IOException (-2146232800)
Failed to bind to address http://[::]:8306: address already in use.
Microsoft.AspNetCore.Connections.AddressInUseException (-2146233079)
Only one usage of each socket address (protocol/network address/port) is normally permitted.
System.Net.Sockets.SocketException (-2147467259)
Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
--- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
--- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.OpenCommunicationListenersAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.System.Fabric.IStatelessServiceInstance.OpenAsync(IStatelessServicePartition partition, CancellationToken cancellationToken)
For more information see: <a href='https://aka.ms/sfhealth' target='_blank'>https://aka.ms/sfhealth</a>
```

**Expected behavior**
Deployment to a 5-node cluster does not incur port binding errors on four nodes.

**Observed  behavior**:
Deployment leads to unhealthy cluster after a few minutes.

**Screenshots**

**Service Fabric Runtime Version:** 
7.2.477.9590

**Environment:**
 - OneBox/Dev cluster]
 - OS: Windows 10 Enterprise
 - Version  20H2, Build 19042.804

If this is a regression, which version did it regress from?

**Additional context**
I am unable to upload the SF cluster logs because they are 42 MB and max allowed is 10 MB. Please let me know where I can drop them.
I'll be happy to make available the GitHub repo with the source code to a team or certain members as collaborators  if given their email addresses.
Deployment via msbuild and PowerShell fails even more spectacularly. The API service won't run at all. Error message is the same: failed to bind to port on 4 of the 5 nodes, but the response to any API call is always a server error (500).

---
Assignees: /cc @microsoft/service-fabric-triage

![SF Health](https://user-images.githubusercontent.com/8224318/114373676-21802780-9b83-11eb-9a64-a943b0e76a34.png)

**Comment by anantshankar17** [comment]
This is by design. On a dev cluster you can't run multiple instances of a service, each using the same port because once an instance binds on that port, all other instances will fail to bind on that port. You should use dynamic ports and not define the static port 8306 in the manifest. If you have to use the static port, then use the 1 node dev cluster instead.
