### ISSUE TITLE
[BUG] Failed to get all the fields of event of type X. Exception info: System.OverflowException: Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by PepijnGramberg** [microsoft/service-fabric#1217]
**Describe the bug**
After a random check of the eventlog there are tons of messages with the same exception.
Each cluster (5 VMs) produces around 600K of these logs each day.

The **bold** part is the only part that differs.

>Failed to get all the fields of event of type **TStore.KeyValueSizeTelemetry**. Exception info: System.OverflowException: Arithmetic operation resulted in an overflow.
   at Tools.EtlReader.ApplicationDataReader.VerifyUnicodeStringReadAndReturnStringLength()
   at Tools.EtlReader.ApplicationDataReader.ReadUnicodeString()
   at FabricDCA.TelemetryUtility.GetEtwEventRecordValue(ApplicationDataReader reader, FieldDefinition fieldDef, String logSourceId)
   at FabricDCA.TelemetryUtility.ReadFieldsFromEventRecord(EventRecord eventRecord, EventDefinition eventDefinition, TraceAggregationConfig traceAggregationConfig, List\`1& numericalFields, List\`1& stringFields, String& diffFieldValueString, String logSourceId).

Types seen in the **bold**, in order of frequency
- TReplicator.Telemetry
- TStateManager.StateProviderDiskSizeTelemetry
- TStateManager.StateProviderCountTelemetry
- TStore.ItemCountTelemetry
- TStore.StoreNotificationsTelemetry
- some more on TStore and TReplicator Telemetries but this less than 1% of the messages.

**Area/Component**:
Eventlog

**To Reproduce**
I am not sure how this happened, or when this started. It does occur on 2 clusters in 2 separate subscriptions.

**Expected behavior**
No exceptions

**Observed  behavior**:
a lot of exceptions

**Screenshots**

**Service Fabric Runtime Version:** 
n/a

**Environment:**
Azure
OS: Windows 2019
Version 8.0.521.9590
NetCore 3.1.15 installed

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by lindgrend** [comment]
Any update on this we are seeing the same.
