### ISSUE TITLE
[BUG] -Run time error after adding a new Actor service to my working SF solution

### ISSUE THREAD

**Issue by sidamr35** [microsoft/service-fabric#1234]
**Describe the bug**
While trying to add a new Actor Service to my Service fabric solution, I am getting the following error during the run time.

  'RunAsync' reported Warning for property 'RunAsyncUnhandledException'.
System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'IFabricServiceManagementClient7'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{332C88B9-BA98-429F-BB50-A562C17476EB}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.Fabric.FabricClient.CreateNativeClient(IEnumerable`1 connectionStringsLocal)
   at System.Fabric.Interop.Utility.<>c__DisplayClass28_0.b__0()
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke(Action action, String functionTag, String functionArgs)
   at System.Fabric.Interop.Utility.RunInMTA(Action action)
   at System.Fabric.FabricClient.InitializeFabricClient(SecurityCredentials credentialArg, FabricClientSettings newSettings, String[] hostEndpointsArg)
   at Microsoft.ServiceFabric.Services.Client.ServicePartitionResolver.<>c.b__21_0()
   at Microsoft.ServiceFabric.Services.Client.ServicePartitionResolver.GetClient()
   at Microsoft.ServiceFabric.Services.Client.ServicePartitionResolver.ResolveHelperAsync(Func`5 resolveFunc, ResolvedServicePartition previousRsp, TimeSpan resolveTimeout, TimeSpan maxRetryInterval, CancellationToken cancellationToken, Uri serviceUri)
   at Microsoft.ServiceFabric.Services.Communication.Client.CommunicationClientFactoryBase`1.GetClientAsync(Uri serviceUri, ServicePartitionKey partitionKey, TargetReplicaSelector targetReplicaSelector, String listenerName, OperationRetrySettings retrySettings, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Client.FabricTransportServiceRemotingClientFactory.GetClientAsync(Uri serviceUri, ServicePartitionKey partitionKey, TargetReplicaSelector targetReplicaSelector, String listenerName, OperationRetrySettings retrySettings, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient`1.GetCommunicationClientAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient`1.InvokeWithRetryAsync[TResult](Func`2 func, CancellationToken cancellationToken, Type[] doNotRetryExceptionTypes)
   at Microsoft.ServiceFabric.Services.Remoting.V2.Client.ServiceRemotingPartitionClient.InvokeAsync(IServiceRemotingRequestMessage remotingRequestMessage, String methodName, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.InvokeAsyncV2(Int32 interfaceId, Int32 methodId, String methodName, IServiceRemotingRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken)
   at Janitor.ScheduledActorService`1.RunAsync(CancellationToken cancellationToken) in C:\Users\siddharth.mathur\Desktop\Tropos.Net\P00000 App Server\SeedCode\Janitor\ScheduledActorService.cs:line 28
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.ExecuteRunAsync(CancellationToken runAsyncCancellationToken)

**Comment by WhitWaldo** [comment]
The exception indicates your Actor's interface isn't supported - is your Actor's interface inheriting from IActor?

**Comment by sidamr35** [comment]
@WhitWaldo, yes my Acotor's class is inheriting from IActor. I was able to resolve problem by upgrading my SF SDK runtime to 8.x.x.
