### ISSUE TITLE
[BUG] -Run time failure on a remoting call from one stateless .net framework service to another within the cluster.

### ISSUE THREAD

**Issue by sidamr35** [microsoft/service-fabric#1246]
I am trying to call a function implemented in a stateless service using IService interface using the following code : 

string OServerProxuURI = Environment.GetEnvironmentVariable("Fabric_ApplicationName") + "/OServer.XXX.XXX.Net";
            ITestRemoting OProxy = ServiceProxy.Create<ITestRemoting>(new System.Uri(OServerProxuURI),new ServicePartitionKey(1));
           
 OProxy.Test();

and I get the following runtime error : 
string OServerProxuURI = Environment.GetEnvironmentVariable("Fabric_ApplicationName") + "/OServer.Epicor.Tropos.Net";
            ITestRemoting OProxy = ServiceProxy.Create<ITestRemoting>(new System.Uri(OServerProxuURI),new ServicePartitionKey(1));
            OProxy.Test();

I get the following sequence of .net runtime errors : 

Could not load file or assembly 'System.Fabric.Management.ServiceModel.XmlSerializers, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Exception from HRESULT: 0x80071BBF
at System.Fabric.Interop.NativeClient.IFabricServiceManagementClient7.EndResolveServicePartition(IFabricAsyncOperationContext context)
at System.Fabric.FabricClient.ServiceManagementClient.ResolveServicePartitionEndWrapper(IFabricAsyncOperationContext context)

This never reached the Test method in the service.

**Service Fabric Runtime Version:** 
8.0.521.9590

**Environment:**
Windows 2016

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by 404-xianjin** [comment]
please help me   ! thank you  ！  I also have some questions about Service Fabric

**Comment by sidamr35** [comment]
Please note that this service already has a running Kestrel endpoint and I am facing a problem while adding a new remoting endpoint.
