### ISSUE TITLE
[BUG] - Installation of Service Fabric Runtime fails

### ISSUE THREAD

**Issue by danielrosatellez** [microsoft/service-fabric#1311]
**Describe the bug**
When trying to install Service Fabric latest version through Web Installer 5.1 it fails. I am running as Administrator. This is the error:

```
1/26/2022 5:58:03 PM,Info,Installing Service Fabric Runtime. Logs written to C:\WINDOWS\TEMP\InstallFabricRuntime_637787986826391722.log
1/26/2022 5:58:04 PM,Info,1/26/2022 12:58:04 PM Running Process: powershell.exe -NoProfile -Command Get-ExecutionPolicy -Scope CurrentUser with timeout 00:01:00
1/26/2022 5:58:04 PM,Info,Running extract in parallel.
1/26/2022 5:58:04 PM,Info,Unpackaging autoextractor...
1/26/2022 5:58:04 PM,Info,Creating temporary runtime directory C:\Program Files\Microsoft Service Fabric.cmmlut1t.isk.
1/26/2022 5:58:04 PM,Info,Extracting runtime cab to C:\Program Files\Microsoft Service Fabric.cmmlut1t.isk...
1/26/2022 5:58:04 PM,Info,1/26/2022 12:58:04 PM Running Process: C:\WINDOWS\TEMP\MicrosoftServiceFabricAutoextractor.exe /L "C:\Program Files\Microsoft Service Fabric.cmmlut1t.isk" /E /Y with timeout 01:00:00
1/26/2022 5:58:11 PM,Info,Current Powershell Execution Policy: RemoteSigned
1/26/2022 5:58:11 PM,Info,Searching for legacy installation registry key.
1/26/2022 5:58:11 PM,Info,Service Fabric Product not detected in registry.
1/26/2022 5:58:13 PM,Error,Exception type: System.UnauthorizedAccessException, Message: Access to the path 'C:\WINDOWS\TEMP\MicrosoftServiceFabricAutoextractor.exe' is denied., Stack:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program.TryExtractExe(String fabricExtractPath)
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program.<>c__DisplayClass36_1.<Main>b__3()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program.Main(String[] args)
1/26/2022 5:58:13 PM,Info,Cleaning temporary directory C:\Program Files\Microsoft Service Fabric.cmmlut1t.isk
Press enter to exit. Process will automatically close after 30 seconds.

```

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by danielrosatellez** [comment]
![image](https://user-images.githubusercontent.com/82245178/151221283-299c33d0-64a6-4bae-b5cf-0b4369710e05.png)

**Comment by danielrosatellez** [comment]
Closed by accident. Reopened since the issue is still ocurring.

**Comment by dmihos** [comment]
@danielrosatellez 
Did you manage to resolve this? 
I'm having the same issue, on a new installation of Windows 11

**Comment by danielrosatellez** [comment]
Unfortunately, as far as I know, SF does not work on ARM.
