### ISSUE TITLE
[BUG] - Docker image with ubuntu 18 doesn't work on mac arm

### ISSUE THREAD

**Issue by fgarciachipi** [microsoft/service-fabric#1326]
**Describe the bug**
Since there isn't an arm image the option is to use the amd64 image with ubuntu 18. The container with the image starts but SF throws errors.

**Area/Component**:
docker image service fabric runtime on mac arm

**To Reproduce**
1. Follow the instructions in the doc: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-mac
2. The container starts but SF never starts

**Expected behavior**
Service Fabric cluster should run in the docker container

**Observed  behavior**:

**Screenshots**
NA

**Service Fabric Runtime Version:** 
8.1.323.1

**Environment:**
 - OneBox/Dev cluster
 - OS: macOS Monterey running docker image with Ubuntu 18.04 
 - Version v12.2.1

If this is a regression, which version did it regress from?

**Additional context**
logs

```
Starting FabricHost
Starting Fabric Host as console application.
Cgroup initialization failed with error 50001, check cgroup mount point
Opening Fabric node.
Opening Fabric node.
Opening Fabric node.
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Opening Fabric node.
Opening Fabric node.
Opening Fabric node.
Unhandled exception. System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at FabricDCA.ContainerManager.CreateContainerFolderWacher() in /source/src/prod/src/managed/DCA/product/host/ContainerManager.cs:line 109
   at FabricDCA.ContainerManager..ctor(AppInstanceManager appInstanceManager, ContainerEnvironment containerEnvironment) in /source/src/prod/src/managed/DCA/product/host/ContainerManager.cs:line 47
   at FabricDCA.Program.Main(String[] args) in /source/src/prod/src/managed/DCA/product/host/Program.cs:line 130
qemu: uncaught target signal 6 (Aborted) - core dumped
```

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by jackbond** [comment]
@fgarciachipi I hate to be the bearer of bad news, but the SF team, if it still exists, does NOT monitor this github. Quite frankly, they could give a ****.

If you need help resolving an issue, your only chance is to file a service ticket.

**Comment by AmirHosseinKarimi1997** [comment]
Still no update on this issue?
@fgarciachipi Did you create any service ticket or something to follow up on this issue?

**Comment by fgarciachipi** [comment]
No, in Azure it works so there isn't a ticket for they to solve. I decided to move to kubernetes.

**Comment by ChillarAnand** [comment]
With mac arm (M1), both ubuntu 18 & ubuntu latest are failing to run with the same message. Any plans to fix this?

**Comment by ChillarAnand** [comment]
Does anyone know any workaround until this is fixed?
