### ISSUE TITLE
[BUG] .NET SDK 6.0.1017 missing on Azure DevOps Hosted VS2017 Agents

### ISSUE THREAD

**Issue by loekd** [microsoft/service-fabric#1359]
**Describe the bug**
Running a unit test code that targets `Microsoft.ServiceFabric.Actors` Version="6.0.1017" results in an error on a hosted VS2017 agent.

**The error:**
```
Unhandled exception. Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\NS_9\Microsoft.ServiceFabric.Data.Impl.dll'. The system cannot find the path specified.
File name: 'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\NS_9\Microsoft.ServiceFabric.Data.Impl.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.ServiceFabric.Data.ReliableStateManager..ctor(StatefulServiceContext serviceContext, ReliableStateManagerConfiguration configuration)

```
This is caused by a mismatch between the Nuget package version and the SDK on the build agent.

**Area/Component**:
programming modes in combination with Azure DevOps

**To Reproduce**
1. Install older SDK version to reproduce the error.
2. Install the latest version to resolve it.

**Expected behavior**
Azure DevOps agents should be equipped with the latest SDK, so we can run unit tests.

**Observed  behavior**:
Azure DevOps agent doesn't have the latest SDK

**Service Fabric Runtime Version:** 
Windows 9.0.1017.9590
Windows .NET SDK 6.0.1017

**If this is a regression, which version did it regress from?**
We've seen this issue before.

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by loekd** [comment]
It's been fixed.
