### ISSUE TITLE
[BUG] write conflict when updating KVS and returning ComException: 0x80071BD6

### ISSUE THREAD

**Issue by smartpcr** [microsoft/service-fabric#1383]
**Describe the bug**
We have a bunch of stateful services, and only one service (MDS) is updating KVS with a specific key. Customer was trying to replace faulty node and did failover of services. We found MDS service is hanging with write KVS error `System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071BD6`:

**Area/Component**:
KVS using managed interface.

**To Reproduce**
Unable to repro but have proc dump.

**Expected behavior**
- Since we have only 1 primary partition of service, there shouldn't be any write conflict (logged error showing same process id).
- Write conflict throws unhandled exception and crashes the service and service should restart itself automatically

**Observed  behavior**:
- there was write conflicts
-  we observed the service is hanging (cannot be terminated, we tried taskkill and won't work, have to reboot the node)

**Screenshots**
N/A

**Service Fabric Runtime Version:** 
```
    <PackageReference Update="Microsoft.ServiceFabric" version="7.2.477" />
    <PackageReference Update="Microsoft.ServiceFabric.Data" version="4.2.477" />
    <PackageReference Update="Microsoft.ServiceFabric.Data.Extensions" version="4.2.477" />
    <PackageReference Update="Microsoft.ServiceFabric.Data.Interfaces" version="4.2.477" />
    <PackageReference Update="Microsoft.ServiceFabric.Diagnostics.Internal" version="4.2.477" />
    <PackageReference Update="Microsoft.ServiceFabric.Services" version="4.2.477" />
```

**Environment:**
 - AzureStack P4 (4 node cluster) v2012, Windows 2019

Stack trace:
```log
System.Fabric.FabricTransientException: Write conflict. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071BD6
   at System.Fabric.Interop.NativeRuntime.IFabricKeyValueStoreReplica8.Update(IFabricTransactionBase transaction, IntPtr key, Int32 valueSizeInBytes, IntPtr value, Int64 checkSequenceNumber)
   at System.Fabric.KeyValueStoreReplica.UpdateHelper(TransactionBase transactionBase, String key, Byte[] value, Int64 checkSequenceNumber)
   at System.Fabric.KeyValueStoreReplica.<>c__DisplayClass71_0.<Update>b__0()
   at System.Fabric.Interop.Utility.<>c__DisplayClass28_0.<WrapNativeSyncInvoke>b__0()
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
   --- End of inner exception stack trace ---
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
   at System.Fabric.KeyValueStoreReplica.Update(TransactionBase transactionBase, String key, Byte[] value, Int64 checkSequenceNumber)
```
---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by smartpcr** [comment]
please ping @xiaodoli via team if this works better, thanks
