### ISSUE TITLE
[BUG] - Start-ServiceFabricRepairTask only accepts -Description of length < 256

### ISSUE THREAD

**Issue by jacksontromero** [microsoft/service-fabric#1450]
**Describe the bug**
There is an undocumented limit to the length of a RepairTasks' Description field of at most 255 characters.

**Area/Component**:
PowerShell, Repair Manager, Repair Task

**To Reproduce**
1. Attempt Start-ServiceFabricRepairTask -NodeNames ___ -CustomAction ___ -Description `x` where `x` is a string of length > 255

**Expected behavior**
String length of any limit (or very large limit) to be accepted

**Observed  behavior**:
Strings above 255 characters cause "Value does not fall within the expected range."  The errors verbatim are below:

```
Start-ServiceFabricRepairTask : Value does not fall within the expected range.
At line:1 char:1
+ Start-ServiceFabricRepairTask -NodeNames "REDACTED" -CustomAct ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Servi...usterConnection:ClusterConnection) [Start-ServiceFabricRepairTask], Argumen
   tException
    + FullyQualifiedErrorId : StartRepairTaskErrorId,Microsoft.ServiceFabric.Powershell.StartRepairTask
```
With more details printed:
```
PSMessageDetails      :
Exception             : System.ArgumentException: Value does not fall within the expected range.
                           at System.Fabric.Interop.Utility.RunInMTA[TResult](Func`1 func)
                           at System.Fabric.Interop.Utility.WrapNativeAsyncInvokeInMTA[TResult](Func`2 beginFunc, Func`2 endFunc,
                        InteropExceptionTracePolicy tracePolicy, CancellationToken cancellationToken, String functionTag)
                           at System.Fabric.FabricClient.RepairManagementClient.CreateRepairTaskAsync(RepairTask repairTask, TimeSpan
                        timeout, CancellationToken cancellationToken)
                           at Microsoft.ServiceFabric.Powershell.ClusterConnection.CreateRepairTaskAsync(RepairTask repairTask, TimeSpan
                        timeout, CancellationToken cancellationToken)
                           at Microsoft.ServiceFabric.Powershell.StartRepairTask.ProcessRecord()
TargetObject          : Microsoft.ServiceFabric.Powershell.ClusterConnection
CategoryInfo          : InvalidArgument: (Microsoft.Servi...usterConnection:ClusterConnection) [Start-ServiceFabricRepairTask],
                        ArgumentException
FullyQualifiedErrorId : StartRepairTaskErrorId,Microsoft.ServiceFabric.Powershell.StartRepairTask
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}





MyCommand             : Start-ServiceFabricRepairTask
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 1
OffsetInLine          : 1
HistoryId             : 120
ScriptName            :
Line                  : Start-ServiceFabricRepairTask -NodeNames "REDACTED" -CustomAction "REDACTED" -Description ';aksdffffffffffffff
                        ffffffffffffffffffffffffffffffffffffl;kjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
                        jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjasdfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
                        d'
PositionMessage       : At line:1 char:1
                        + Start-ServiceFabricRepairTask -NodeNames "REDACTED" -CustomAct ...
                        + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PSScriptRoot          :
PSCommandPath         :
InvocationName        : Start-ServiceFabricRepairTask
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition :



00000000000000000000000000000000000000000000000000000000000000000000000000000000


Message        : Value does not fall within the expected range.
ParamName      :
Data           : {}
InnerException :
TargetSite     : TResult RunInMTA[TResult](System.Func`1[TResult])
StackTrace     :    at System.Fabric.Interop.Utility.RunInMTA[TResult](Func`1 func)
                    at System.Fabric.Interop.Utility.WrapNativeAsyncInvokeInMTA[TResult](Func`2 beginFunc, Func`2 endFunc,
                 InteropExceptionTracePolicy tracePolicy, CancellationToken cancellationToken, String functionTag)
                    at System.Fabric.FabricClient.RepairManagementClient.CreateRepairTaskAsync(RepairTask repairTask, TimeSpan timeout,
                 CancellationToken cancellationToken)
                    at Microsoft.ServiceFabric.Powershell.ClusterConnection.CreateRepairTaskAsync(RepairTask repairTask, TimeSpan timeout,
                 CancellationToken cancellationToken)
                    at Microsoft.ServiceFabric.Powershell.StartRepairTask.ProcessRecord()
HelpLink       :
Source         : System.Fabric
HResult        : -2147024809
```

**Service Fabric Runtime Version:** 
9.1.1799.9590

**Environment:**
 - Standalone
 - OS: Tested on Windows 11 (local cluster) and Windows Datacenter 2019

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by jacksontromero** [comment]
For what it's worth, -CustomAction has an undocumented max string length of 63 as well
