### ISSUE TITLE
[BUG] - Cannot Start Service Fabric Local Cluster from SDK utility PS modules when Windows server 2022 image is used.

### ISSUE THREAD

**Issue by Kamalesh-r-mysore** [microsoft/service-fabric#1461]
Not able to start service fabric local cluster from SDK utility PS modules when Windows server 2022 is used as runner image in Azure Pipeline.

Excpetion:
2023-09-08T09:11:36.2495178Z Getting existing application status: Stopped
2023-09-08T09:11:37.3358300Z _--------------------------------------------_
2023-09-08T09:11:37.3365607Z Local Service Fabric Cluster is not setup...
2023-09-08T09:11:37.3373597Z Please wait while we setup the Local Service Fabric Cluster. This may take few minutes...
2023-09-08T09:11:37.3592738Z Performing Stop-Service on: FabricHostSvc . This may take a few minutes...
2023-09-08T09:11:37.9066646Z Opening TraceWriter FabricDeployer, path C:\ProgramData\Microsoft Service Fabric\log\Traces\FabricDeployer-638297610976848133.trace
2023-09-08T09:11:50.0624933Z _**_Unable to start fabric host service because System.InvalidOperationException: Cannot start service FabricHostSvc on computer '.'. ---> System.ComponentModel.Win32Exception: The service did not respond to the start or control request in a timely fashion_**_
2023-09-08T09:11:50.0625970Z    --- End of inner exception stack trace ---
2023-09-08T09:11:50.0626319Z    at System.ServiceProcess.ServiceController.Start(String[] args)
2023-09-08T09:11:50.0626710Z    at System.Fabric.FabricDeployer.FabricDeployerServiceController.StartHostSvc(String machineName)
2023-09-08T09:11:50.0639881Z Unable to stop FabricHostSvc service because System.InvalidOperationException: Cannot stop FabricHostSvc service on computer '.'. ---> System.ComponentModel.Win32Exception: The service has not been started
2023-09-08T09:11:50.0640542Z    --- End of inner exception stack trace ---
2023-09-08T09:11:50.0640956Z    at System.ServiceProcess.ServiceController.Stop()
2023-09-08T09:11:50.0641365Z    at System.Fabric.FabricDeployer.FabricDeployerServiceController.Stop(String serviceName, String machineName)
2023-09-08T09:11:50.0671133Z Closing TraceWriter FabricDeployer, path C:\ProgramData\Microsoft Service Fabric\log\Traces\FabricDeployer-638297610976848133.trace
2023-09-08T09:11:50.3084606Z 
2023-09-08T09:11:50.3104521Z Using Cluster Data Root: C:\SfDevCluster\Data
2023-09-08T09:11:50.3112438Z Using Cluster Log Root: C:\SfDevCluster\Log
2023-09-08T09:11:50.3116189Z 
2023-09-08T09:11:50.4058686Z The generated json path is C:\Users\cloudtest\AppData\Local\Temp\tmpCBDF.tmp.json
2023-09-08T09:11:51.2791794Z Processing and validating cluster config.
2023-09-08T09:11:52.2950022Z Opening TraceWriter FabricDeployer, path C:\ProgramData\Microsoft Service Fabric\log\Traces\FabricDeployer-638297611121697603.trace
2023-09-08T09:11:52.6269862Z Closing TraceWriter FabricDeployer, path C:\ProgramData\Microsoft Service Fabric\log\Traces\FabricDeployer-638297611121697603.trace
2023-09-08T09:11:52.6282693Z Performing Stop-Service on: FabricHostSvc . This may take a few minutes...
2023-09-08T09:11:52.6483535Z Opening TraceWriter FabricDeployer, path C:\SfDevCluster\Log\Traces\FabricDeployer-638297611126387123.trace
2023-09-08T09:11:52.9968188Z Closing TraceWriter FabricDeployer, path C:\SfDevCluster\Log\Traces\FabricDeployer-638297611126387123.trace
2023-09-08T09:11:52.9972921Z Create node configuration succeeded
2023-09-08T09:11:53.0284386Z Performing Start-Service on: FabricHostSvc . This may take a few minutes...
2023-09-08T09:22:03.6771165Z PerformServiceOperationWithWaitforStatus : Could not perform the operation:Start-Service on the service:FabricHostSvc.
2023-09-08T09:22:03.6771860Z At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:950 char:5
2023-09-08T09:22:03.6772338Z +     PerformServiceOperationWithWaitforStatus "FabricHostSvc" "Start-S ...
2023-09-08T09:22:03.6772666Z +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-09-08T09:22:03.6773114Z     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
2023-09-08T09:22:03.6773469Z     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,PerformServiceOperationWithWaitforStat 
2023-09-08T09:22:03.6773718Z    us
2023-09-08T09:22:03.6773910Z  
2023-09-08T09:22:03.8549896Z ##[error]PowerShell exited with code '1'.

**Service Fabric Runtime Version:** 
ex: 9.1 CU1 ( 9.1.1833.9590)*

**Environment:**
 - Local Cluster
 - OS: Windows server 2022
 - Version

The script used is:
**Set-LocalClusterReady -createOneNodeCluster $true -IsLocalClusterSetup $false**

The same script is working fine in Windows server 2019.
----------------------------------------------------------------------------------------------------------------------------------------------
Assignees: /cc @microsoft/service-fabric-triage

**Comment by youyuanwu** [comment]
There is a dll conflict issue for SF runtime dlls and MySQL dlls on github action runner image. For ADO the issue might be similar.
The work around is to remove the MySQL dlls.
See https://github.com/youyuanwu/service-fabric-rs/blob/3f2bef6eaa5cbbb1b97ee27fb87205ecc9c5ebdb/.github/workflows/build.yaml#L32 For example.
