### ISSUE TITLE
[BUG] Error installing new version of Service Fabric SDK 7.0.1816 (MicrosoftServiceFabricSDK.7.0.1816.msi)

### ISSUE THREAD

**Issue by dheerajbhavsar** [microsoft/service-fabric#1464]
**Error while installing Service Fabic Sdk latest version MicrosoftServiceFabricSDK.7.0.1816 **

**SDK**:
MicrosoftServiceFabricSDK.7.0.1816 

**To Reproduce**
choco install service-fabric-sdk

**Expected behavior**

**Observed  behavior**:
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Hashes match.
Hashes match.
Installing service-fabric-sdk...
WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\service-fabric-sdk_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
ERROR: Running ["C:\WINDOWS\System32\msiexec.exe" /i "C:\Users\dheer\AppData\Local\Temp\chocolatey\service-fabric-sdk\7.0.1816\MicrosoftServiceFabricSDK.7.0.1816.msi" /quiet /qn /norestart /l*v "C:\Users\dheer\AppData\Local\Temp\chocolatey\service-fabric-sdk\7.0.1816\install.log" IACCEPTEULA=yes ] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\service-fabric-sdk_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
The install of service-fabric-sdk was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\service-fabric-sdk\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - service-fabric-sdk (exited 1603) - Error while running 'C:\ProgramData\chocolatey\lib\service-fabric-sdk\tools\chocolateyInstall.ps1'.
 See log for details.

**Screenshots**

**Service Fabric Runtime Version:** 
MicrosoftServiceFabric.10.0.1816.9590

**Environment:**
 - Dev cluster
 - OS: Windows 11
 - Version 10

If this is a regression, which version did it regress from?

**Additional context**
Logs:
Part of logs where error occures:

MSI (s) (64:B8) [15:49:50:882]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSIB7BE.tmp, Entrypoint: CheckWithRuntimeCA
MSI (s) (64:58) [15:49:50:882]: Generating random cookie.
MSI (s) (64:58) [15:49:50:886]: Created Custom Action Server with PID 22244 (0x56E4).
MSI (s) (64:BC) [15:49:50:898]: Running as a service.
MSI (s) (64:BC) [15:49:50:900]: Hello, I'm your 64bit Impersonated custom action server.
Action start 15:49:50: CompatibilityCheckAction.
SFXCA: Extracting custom action to temporary directory: C:\WINDOWS\Installer\MSIB7BE.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action SdkRuntimeCompatibilityCheck!Microsoft.ServiceFabric.SdkRuntimeCompatibilityCheck.CompatibilityCheckCA.CheckWithRuntimeCA
Error: could not load custom action class Microsoft.ServiceFabric.SdkRuntimeCompatibilityCheck.CompatibilityCheckCA from assembly: SdkRuntimeCompatibilityCheck
System.IO.FileLoadException: Could not load file or assembly 'SdkRuntimeCompatibilityCheck, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
File name: 'SdkRuntimeCompatibilityCheck, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
The Zone of the assembly that failed was:
MyComputer
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.AppDomain.Load(String assemblyString)
   at Microsoft.Deployment.WindowsInstaller.CustomActionProxy.GetCustomActionMethod(Session session, String assemblyName, String className, String methodName)

CustomAction CompatibilityCheckAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (s) (64:3C) [15:49:51:438]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (64:3C) [15:49:51:438]: Machine policy value 'DisableRollback' is 0
MSI (s) (64:3C) [15:49:51:438]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
Action ended 15:49:51: CompatibilityCheckAction. Return value 3.
MSI (s) (64:3C) [15:49:51:439]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (64:3C) [15:49:51:439]: No System Restore sequence number for this installation.
MSI (s) (64:3C) [15:49:51:439]: Unlocking Server
Action ended 15:49:51: INSTALL. Return value 3.
Property(S): UpgradeCode = {47294815-2B47-4AB5-B37E-6BECE57E8A03}

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by williamoconnorme** [comment]
Related #1462
