### ISSUE TITLE
[BUG] - Unit testing `ReliableStateManager` no longer possible in v7.1.2448

### ISSUE THREAD

**Issue by loekd** [microsoft/service-fabric#1512]
**Describe the bug**
Up until v7.1.2338 I was able to run unit tests for `ReliableStateManager` using the helper code from [ServiceFabric.Mocks](https://github.com/loekd/ServiceFabric.Mocks)
(I'm the original author)

During creation, ReliableStateManager makes this call:
```csharp
string codePath = System.Fabric.Common.FabricEnvironment.GetCodePath();
```
This call causes a null reference exception during test:

```shell
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Fabric.Interop.NativeTypes.FromNativeString(IFabricStringResult result)
   at System.Fabric.Interop.StringResult.FromNative(IFabricStringResult nativeResult)
   at System.Fabric.Common.FabricEnvironment.GetCodePathHelper(String machineName)
   at System.Fabric.Common.FabricEnvironment.<>c__DisplayClass6_0.<GetCodePath>b__0()
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
   at System.Fabric.Common.FabricEnvironment.GetCodePath(String machineName)
   at System.Fabric.Common.FabricEnvironment.GetCodePath()
```

**Area/Component**:
Reliable Services - Unit testing

**To Reproduce**
- Go to https://github.com/loekd/ServiceFabric.Mocks
- Create a Codespace for branch `dependabot/nuget/Microsoft.ServiceFabric.Actors-7.1.2448`
- Run `dotnet test`
- Observe the null reference exceptions

**Expected behavior**

Up until this version, I was able to use reflection to create usable objects for unit test purposes. This is no longer the case.

**Observed  behavior**:
n/a

**Screenshots**

**Service Fabric Runtime Version:** 
7.1.2448

**Environment:**
 - Ubuntu 20.04] 

**Additional context**
I realize this is not a MS supported scenario, but a lot of people depend on the package for their SF testing. I'd really love to keep this package alive. It's blocking me from releasing a version that works with `v7.1.2448`.
Hope you are willing to help.

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by loekd** [comment]
It appears to be an issue on my end. I'll close this issue. Sorry for any inconvenience.
