### ISSUE TITLE
[SOLVED] Trying to setup a new standalone service fabric cluster On-Premises

### ISSUE THREAD

**Issue by licjapodaca** [Microsoft/service-fabric#158]
I'm trying to setup a new standalone service fabric cluster On-Premises but before creates the powershell script `TestConfiguration.ps1` throws me the following trace:

```
2018/06/19-22:21:36.157,Info,4120,SystemFabricDeployer.SFDeployer,Running Best Practices Analyzer...
2018/06/19-22:21:36.161,Verbose,4120,SystemFabricDeployer.SFDeployer,Validating executing user is an Administrator.
2018/06/19-22:21:36.164,Verbose,4120,SystemFabricDeployer.SFDeployer,Converting JSON config to model.
2018/06/19-22:21:36.504,Verbose,4120,SystemFabricDeployer.SFDeployer,Validating machines are reachable and have opened required ports.
2018/06/19-22:21:36.514,Verbose,4120,SystemFabricDeployer.SFDeployer,Validating each machine has RemoteRegistry service enabled.
2018/06/19-22:21:36.530,Verbose,4120,SystemFabricDeployer.SFDeployer,Validating each machine has Windows Firewall MpsSvc service enabled.
2018/06/19-22:21:36.549,Verbose,4120,SystemFabricDeployer.SFDeployer,Verifying remote procedure call access against cluster machines.
2018/06/19-22:21:36.587,Verbose,4120,SystemFabricDeployer.SFDeployer,Validating against installation conflicts on each machine.
2018/06/19-22:21:36.686,Verbose,4120,SystemFabricDeployer.SFDeployer,Validating Fabric is not already set up on target machines.
2018/06/19-22:21:36.694,Verbose,4692,SystemFabricDeployer.SFDeployer,IsFabricInstalled on machine SVR-4GSF-C hit FabricException. Proceeding anyway. Details: System.Fabric.FabricException: FabricDataRoot is not provided or properly set. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C59
	   at System.Fabric.Interop.NativeCommon.FabricGetDataRoot2(IntPtr machineName)
	   at System.Fabric.Common.FabricEnvironment.GetDataRootHelper(String machineName)
	   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
	   --- End of inner exception stack trace ---
	   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
	   at System.Fabric.NodeConfiguration.GetNodeConfiguration(String machineName)
	   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility.IsFabricInstalled(String machineName).
2018/06/19-22:21:36.694,Verbose,4120,SystemFabricDeployer.SFDeployer,IsFabricInstalled on machine SVR-4GSF-B hit FabricException. Proceeding anyway. Details: System.Fabric.FabricException: FabricDataRoot is not provided or properly set. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C59
	   at System.Fabric.Interop.NativeCommon.FabricGetDataRoot2(IntPtr machineName)
	   at System.Fabric.Common.FabricEnvironment.GetDataRootHelper(String machineName)
	   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
	   --- End of inner exception stack trace ---
	   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
	   at System.Fabric.NodeConfiguration.GetNodeConfiguration(String machineName)
	   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility.IsFabricInstalled(String machineName).
2018/06/19-22:21:36.694,Verbose,4692,SystemFabricDeployer.SFDeployer,Fabric is set up on machine SVR-4GSF-C: False
2018/06/19-22:21:36.694,Verbose,4120,SystemFabricDeployer.SFDeployer,Fabric is set up on machine SVR-4GSF-B: False
2018/06/19-22:21:36.694,Verbose,4156,SystemFabricDeployer.SFDeployer,IsFabricInstalled on machine SVR-4GSF-E hit FabricException. Proceeding anyway. Details: System.Fabric.FabricException: FabricDataRoot is not provided or properly set. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C59
	   at System.Fabric.Interop.NativeCommon.FabricGetDataRoot2(IntPtr machineName)
	   at System.Fabric.Common.FabricEnvironment.GetDataRootHelper(String machineName)
	   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
	   --- End of inner exception stack trace ---
	   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
	   at System.Fabric.NodeConfiguration.GetNodeConfiguration(String machineName)
	   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility.IsFabricInstalled(String machineName).
2018/06/19-22:21:36.694,Verbose,772,SystemFabricDeployer.SFDeployer,IsFabricInstalled on machine SVR-4GSF-D hit FabricException. Proceeding anyway. Details: System.Fabric.FabricException: FabricDataRoot is not provided or properly set. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C59
	   at System.Fabric.Interop.NativeCommon.FabricGetDataRoot2(IntPtr machineName)
	   at System.Fabric.Common.FabricEnvironment.GetDataRootHelper(String machineName)
	   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
	   --- End of inner exception stack trace ---
	   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
	   at System.Fabric.NodeConfiguration.GetNodeConfiguration(String machineName)
	   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility.IsFabricInstalled(String machineName).
2018/06/19-22:21:36.694,Verbose,4156,SystemFabricDeployer.SFDeployer,Fabric is set up on machine SVR-4GSF-E: False
2018/06/19-22:21:36.694,Verbose,772,SystemFabricDeployer.SFDeployer,Fabric is set up on machine SVR-4GSF-D: False
2018/06/19-22:21:37.293,Verbose,3932,SystemFabricDeployer.SFDeployer,IsFabricInstalled on machine SVR-4GSF-A hit FabricException. Proceeding anyway. Details: System.Fabric.FabricException: FabricDataRoot is not provided or properly set. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C59
	   at System.Fabric.Interop.NativeCommon.FabricGetDataRoot2(IntPtr machineName)
	   at System.Fabric.Common.FabricEnvironment.GetDataRootHelper(String machineName)
	   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
	   --- End of inner exception stack trace ---
	   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
	   at System.Fabric.NodeConfiguration.GetNodeConfiguration(String machineName)
	   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility.IsFabricInstalled(String machineName).
2018/06/19-22:21:37.293,Verbose,3932,SystemFabricDeployer.SFDeployer,Fabric is set up on machine SVR-4GSF-A: False
2018/06/19-22:21:37.301,Info,4120,SystemFabricDeployer.SFDeployer,Best Practices Analyzer completed successfully.
```

What means the part `FabricException. Proceeding anyway. Details: System.Fabric.FabricException: FabricDataRoot is not provided or properly set.`

Someone knows something about it.

Greetings

Service Fabric version: Microsoft.Azure.ServiceFabric.WindowsServer.6.2.283.9494
5 Nodes with WIndows Server 2016

ClusterConfig.json
```json
{
	"name": "ServiceFabric",
	"clusterConfigurationVersion": "1.0.0",
	"apiVersion": "10-2017",
	"nodes": [
		{
			"nodeName": "SVR-4GSF-A",
			"nodeTypeRef": "NodeType0",
			"iPAddress": "SVR-4GSF-A",
			"faultDomain": "fd:/dc1/r0",
			"upgradeDomain": "UD1"
		},
		{
			"nodeName": "SVR-4GSF-B",
			"nodeTypeRef": "NodeType0",
			"iPAddress": "SVR-4GSF-B",
			"faultDomain": "fd:/dc1/r1",
			"upgradeDomain": "UD2"
		},
		{
			"nodeName": "SVR-4GSF-C",
			"nodeTypeRef": "NodeType0",
			"iPAddress": "SVR-4GSF-C",
			"faultDomain": "fd:/dc1/r2",
			"upgradeDomain": "UD3"
		},
		{
			"nodeName": "SVR-4GSF-D",
			"nodeTypeRef": "NodeType0",
			"iPAddress": "SVR-4GSF-D",
			"faultDomain": "fd:/dc1/r3",
			"upgradeDomain": "UD4"
		},
		{
			"nodeName": "SVR-4GSF-E",
			"nodeTypeRef": "NodeType0",
			"iPAddress": "SVR-4GSF-E",
			"faultDomain": "fd:/dc1/r4",
			"upgradeDomain": "UD5"
		}
	],
	"properties": {
		//"enableTelemetry": false,
		//"fabricClusterAutoupgradeEnabled": false,
		"diagnosticsStore": {
			"metadata": "Please replace the diagnostics file share with an actual file share accessible from all cluster machines. For example, \\\\machine1\\DiagnosticsStore.",
			"dataDeletionAgeInDays": "7",
			"storeType": "FileShare",
			"isEncrypted": "false",
			"connectionstring": "E:\\SF\\DiagnosticsStore"
		},
		"security": {
			"clusterCredentialType": "Windows",
			"serverCredentialType": "Windows",
			"windowsIdentities": {
				"clusterIdentity": "bts\\ServiceFabric",
				"clientIdentities": [
					{
						"isAdmin": true,
						"identity": "bts\\Justicia4G - Arquitecto de Software"
					},
					{
						"isAdmin": false,
						"identity": "bts\\Justicia4G - Desarrollador"
					},
					{
						"isAdmin": false,
						"identity": "bts\\Justicia4G - Ingeniero de Pruebas"
					}
				]
			}
		},
		"nodeTypes": [
			{
				"name": "NodeType0",
				"clientConnectionEndpointPort": "19000",
				"httpGatewayEndpointPort": "19080",
				"reverseProxyEndpointPort": "19081",
				"leaseDriverEndpointPort": "19002",
				"clusterConnectionEndpointPort": "19001",
				"serviceConnectionEndpointPort": "19003",
				"applicationPorts": {
					"startPort": "50000",
					"endPort": "59999"
				},
				"ephemeralPorts": {
					"startPort": "60000",
					"endPort": "65535"
				},
				"isPrimary": true
			}
		],
		"fabricSettings": [
			{
				"name": "Setup",
				"parameters": [
					{
						"name": "FabricDataRoot",
						"value": "E:\\SF"
					},
					{
						"name": "FabricLogRoot",
						"value": "E:\\SF\\Log"
					}
				]
			}
		],
		"addOnFeatures": [
			"DnsService",
			"RepairManager"
		]
	}
}
```

**Comment by jkochhar** [comment]
That only means we were checking for pre-existing data root from previous installations. The BPA check did seem to complete successfully. Did you hit issues setting up the cluster?

**Comment by licjapodaca** [comment]
Hi @jkochhar , for some reason the VMs that represent the nodes of the Service Fabric cluster something was in a bad way, so I proceed to format and reinstall the OS but this time I installed Windows Server 2016 **DATACENTER** in every VM activating the windows features (Containers and HyperV) to manage Docker Containers and this time the installation process was successful.

I don't know if the problem was the edition of the OS, before was Windows Server 2016 Standard edition and now is Windows Server 2016 Datacenter.

Greetings
