### ISSUE TITLE
SFRPStreamChannel Exceptions in Upgrade Service

### ISSUE THREAD

**Issue by charstar** [Microsoft/service-fabric#166]
I've been periodically experiencing warnings and errors in the upgrade service with errors similar to: 
Error event: SourceId='UpgradeService.Primary', Property='SFRPStreamChannel'. Exception encountered: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

I've previously contacted Azure support around this and received advice around ensuring firewall rules for 168.63.129.16, and allowing outbound traffic to the westus.servicefabric.azure.com IP addresses, however this hasn't seemed to fix the issue.

Is there anything else I'm missing here? Thanks.

**Comment by mchiriac-msft** [comment]
Can you provide following details?
- cluster ARM resource ID
- cluster location
- time interval when the error was seen

**Comment by charstar** [comment]
Cluster ID: f4dcb896-4265-4c68-a4ec-a0d1f8096c21
Location: West US
Time: Most recently, 2018-07-02 1250-1310PDT (1950-2010UTC)

Thanks for your help!

**Comment by mchiriac-msft** [comment]
This is a known issue that we are tracking.

The communication for SFRPStreamChannel created between UpgradeService and ServiceFabric ARM resource provider (SFRP) is monitored. If continuous failures are detected, an error health event is raised. The detection logic is too sensitive and needs rework. We will release a fix for it with ServiceFabric 6.3 CU1 runtime. Date for its release is yet to be established.

You can ignore the health error report as it is transient and should not have an impact on the management operations performed for application and cluster. I checked the cluster and applications and they were all healthy. 

Your cluster is pinned to ServiceFabric 6.1. 
UserSelectedCodeVersion = 6.1.456.9494
UpgradeMode = Manual

In order to take the fix you will have to update UserSelectedCodeVersion with the 6.3 CU1 version and perform an ARM cluster deployment. The alternative is the use the auto upgrade mode and SFRP will automatically upgrade the cluster to take the fix when available.

**Comment by pksorensen** [comment]
I am seeing it too, whats the impact? does it matter?

**Comment by m1stegmann** [comment]
We got the following exception every two or three days. 
How to deal with this error?

SF Version: 6.3.176.9494
With a five node production cluster with D13V2 instances

Error event: SourceId='UpgradeService.Primary', Property='SFRPStreamChannel'.
Exception encountered: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.UpgradeService.WrpStreamChannel.d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Fabric.UpgradeService.WrpStreamChannel.d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Fabric.UpgradeService.WrpStreamChannel.d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Fabric.UpgradeService.ClusterCoordinator.d__16.MoveNext()

**Comment by mchiriac-msft** [comment]
The issue should be transient. It will not impact the deployed cluster or applications.
The health error report should clear automatically.

UpgradeService is timing out the calls against the ServiceFabric resource provider in ARM to collect the stream channel request. Azure Portal or the cluster Service Fabric Explorer(SFX) might take longer to show the runtime view of the cluster. 

@pksorensen/@m1stegmann do you still see the issue on your clusters? If so can you provide the cluster ARM resource ID and the region?

**Comment by pksorensen** [comment]
@mchiriac-msft  Nope, i dont see it any more.

However, i did have the problem that my ARM deployment did not work while the error was ongoing ?

As soon as the error was gone, i could do a ARM deployment of application again.

**Comment by mchiriac-msft** [comment]
@pksorensen can you provide an ARM correlation ID for the deployment that failed while the error was ongoing? I'll look to see what happened.
