### ISSUE TITLE
.NET Core 2.1 fails on linux cluster.

### ISSUE THREAD

**Issue by git-heath** [Microsoft/service-fabric#182]
I have a simple rest service deployed to an ubuntu service fabric cluster which starts perfectly when using .NET core version 2.0 but fails with the following error with version 2.1. Is 2.1 officially supported for a linux cluster ? I could not find this information anywhere. Note that 2.1 works on our Windows cluster.

`Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false.
Replica had multiple failures during open on _NodeType2_2. API call: IStatelessServiceInstance.Open(); Error = System.ArgumentException (-2147024809)
Item has already been added. Key in dictionary: 'LD_LIBRARY_PATH'  Key being added: 'LD_LIBRARY_PATH'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Environment.ToHashtable(IEnumerable`1 pairs)
   at Microsoft.Extensions.Configuration.EnvironmentVariables.EnvironmentVariablesConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder..ctor()
   at HelloWorld.HelloWorld.<>c__DisplayClass1_0.b__1(String url, AspNetCoreCommunicationListener listener) in c:\users\davies\source\repos\HelloWorldCloud\HelloWorld\HelloWorld.cs:line 38
   at Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.OpenCommunicationListenersAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.System.Fabric.IStatelessServiceInstance.OpenAsync(IStatelessServicePartition partition, CancellationToken cancellationToken)
For more information see: http://aka.ms/sfhealth`

**Comment by git-heath** [comment]
Issue posted on https://github.com/Azure/service-fabric-issues/issues/1178
