### ISSUE TITLE
Could not load type 'Microsoft.ServiceFabric.Services.Remoting.RemotingListener' 

### ISSUE THREAD

**Issue by hanxinimm** [Microsoft/service-fabric#184]
System.TypeInitializationException: The type initializer for 'Security.ActorModel.RegisterActor' threw an exception. ---> System.TypeLoadException: Could not load type 'Microsoft.ServiceFabric.Services.Remoting.RemotingListener' from assembly 'Microsoft.ServiceFabric.Services.Remoting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.Reflection.CustomAttribute._GetPropertyOrFieldData(RuntimeModule pModule, Byte** ppBlobStart, Byte* pBlobEnd, String& name, Boolean& bIsProperty, RuntimeType& type, Object& value)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
   at Microsoft.ServiceFabric.Actors.Remoting.ActorRemotingProviderAttribute.GetProvider(IEnumerable`1 types)
   at Microsoft.ServiceFabric.Actors.Client.ActorProxyFactory.GetOrSetProxyFactory(Type actorInterfaceType)
   at Microsoft.ServiceFabric.Actors.Client.ActorProxyFactory.CreateActorProxy[TActorInterface](Uri serviceUri, ActorId actorId, String listenerName)
   at Microsoft.ServiceFabric.Actors.Client.ActorProxy.Create[TActorInterface](ActorId actorId, Uri serviceUri, String listenerName)
   at Security.ActorModel.RegisterActor..cctor() in D:\LotteryCloud\SecurityCenter\Command\Server\Security.ActorModel\Actors\RegisterActor.cs:line 38
   --- End of inner exception stack trace ---
   at Security.ActorModel.RegisterActor..ctor(ActorService actorService, ActorId actorId, Repository`2 repository, IDistributedCache distributedCache) in D:\LotteryCloud\SecurityCenter\Command\Server\Security.ActorModel\Actors\RegisterActor.cs:line 47
   at Security.ActorModel.Program.<>c__DisplayClass0_0.<Main>b__2(ActorService actorService, ActorId actorId) in D:\LotteryCloud\SecurityCenter\Command\Server\Security.ActorModel\Program.cs:line 50
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.GetOrCreateActor(ActorId actorId, Boolean timerUse, Boolean createDummyActor)
   at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.DispatchToActorAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Boolean createIfRequired, Func`3 actorFunc, String callContext, Boolean timerCall, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Remoting.Runtime.ServiceRemotingCancellationHelper.DispatchRequest[T](Int32 interfaceId, Int32 methodId, String callContext, Func`2 dispatchFunc)
   at Microsoft.ServiceFabric.Actors.Remoting.V2.Runtime.ActorServiceRemotingDispatcher.HandleActorMethodDispatchAsync(IActorRemotingMessageHeaders messageHeaders, IServiceRemotingRequestMessageBody msgBody)
   at Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Runtime.FabricTransportMessageHandler.RequestResponseAsync(FabricTransportRequestContext requestContext, FabricTransportMessage fabricTransportMessage)

Microsoft.ServiceFabric.Actors  3.2.162

**Comment by suchiagicha** [comment]
Its the Duplicate issue : https://github.com/Microsoft/service-fabric-services-and-actors-dotnet/issues/141#issuecomment-407471186.

**Comment by VipulM-MSFT** [comment]
The duplicate issue is resolved, closing this issue.
