### ISSUE TITLE
On Premise Add Node gMSA Issues

### ISSUE THREAD

**Issue by justinoverton** [microsoft/service-fabric#229]
Can someone please document all of the security and permissions requirements for properly running fabric secured with gMSA? 

The following is what I've had to do so far to just add a node, it is long and complicated. I have a on premise cluster secured by gMSA setup and wanted to add a new node.

It failed with no error message on the powershell client, but after digging a lot I found the following trace:

```
2018-9-27 17:03:39.799,Warning,10992,2500,UpgradeOrchestrationService.UOSMessageProcessor,ProcessStartUpgradeAsync exception: System.AggregateException: One or more errors occurred. ---> System.Security.SecurityException: Requested registry access is not allowed.
	   at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
	   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
	   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility.<>c__DisplayClass14_1.<IsMsiInstalled>b__0(String machineName)
	   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
	   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
	   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
	   --- End of inner exception stack trace ---
	   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
	   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
	   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
	   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility.IsMsiInstalled(IEnumerable`1 machineNames)
	   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneSettingsValidator.ValidateAddedNodes(NodeList nodesFromFM, List`1 addedNodes, String fabricDataRoot)
	   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneSettingsValidator.<ValidateTopologyAsync>d__49.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneSettingsValidator.<ValidateUpdateFrom>d__21.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Fabric.UpgradeOrchestration.Service.UpgradeOrchestrationMessageProcessor.<ValidateModel>d__15.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Fabric.UpgradeOrchestration.Service.UpgradeOrchestrationMessageProcessor.<ProcessStartClusterConfigurationUpgradeAsync>d__8.MoveNext()
	---> (Inner Exception #0) System.Security.SecurityException: Requested registry access is not allowed.
	   at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
	   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
	   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility.<>c__DisplayClass14_1.<IsMsiInstalled>b__0(String machineName)
	   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
	   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
	   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
	The Zone of the assembly that failed was:
	MyComputer<---
	
	---> (Inner Exception #1) System.Security.SecurityException: Requested registry access is not allowed.
	   at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
	   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
	   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneUtility.<>c__DisplayClass14_1.<IsMsiInstalled>b__0(String machineName)
	   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
	   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
	   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
	The Zone of the assembly that failed was:
	MyComputer<---
```
I took at event logs and everywhere I could to determine which registry key was the issue. Gave the gMSA service user local admin on the new node, and all sorts of things with no luck.

Eventually I found some extra security (that has no log when it fails) that you have to put allowed remote registry reads into:

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurePipeServers\winreg\AllowedPaths
```
Then I had to dig around in the source of the Microsoft.ServiceFabric.DeploymentManager assembly to determine which registry paths it needed access to and add those paths to the key.

Now I'm getting the following exception (found in the event log thankfully) when trying to do the configuration upgrade to add the node:

```
System.Fabric.FabricDeployer.ClusterManifestValidationException: Cluster manifest validation failed with exception System.ArgumentException: Loader exception: System.IO.FileNotFoundException: Could not load file or assembly 'NetFwTypeLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'NetFwTypeLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.WriteError(String format, Object[] args)
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.RunOtherConfigurationValidatorsInTheAssembly()
   at System.Fabric.Management.WindowsFabricValidator.FabricSettingsValidator.ValidateSettings()
   at System.Fabric.Management.WindowsFabricValidator.FabricValidator.Validate()
   at System.Fabric.FabricDeployer.FabricValidatorWrapper.ValidateAndEnsureDefaultImageStore()
   at System.Fabric.FabricDeployer.FabricValidatorWrapper.ValidateAndEnsureDefaultImageStore()
   at System.Fabric.FabricDeployer.ConfigureOperation.OnExecuteOperation(DeploymentParameters parameters, ClusterManifestType clusterManifest, Infrastructure infrastructure)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disableFileTrace)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.NewNodeConfigurationInner(String clusterManifestPath, String infrastructureManifestPath, String jsonClusterConfigPath, String fabricDataRoot, String fabricLogRoot, String fabricHostCredentialUser, SecureString fabricHostCredentialPassword, Boolean runFabricHostServiceAsManual, Boolean removeExistingConfiguration, FabricPackageType fabricPackageType, String fabricPackageRoot, String machineName, String bootstrapPackagePath)
```

Is this also a permissions issue?

**Comment by VipulM-MSFT** [comment]
What is the version of Service Fabric? @gkhanna79 to follow up.

**Comment by Angelicvorian** [comment]
@justinoverton  I've had a similar issue and it was fixed by ensuring the nodename and nodetype were not identical.
I've used FQDN as the nodename and IPaddress as the IPAddressorFQDN values and my gMSA cluster now allows nodes to add successfully.
I used the method as discussed in the MS docs, just using a ClusterConfiguation Upgrade to add the node and it works now.
gMSA account is installed on each new node to be added, it's not added as a local admin on the machine.
My account running the clusterconfig upgrade is a domain admin and also a member of the group used as admin in the identity section.

**Comment by justinoverton** [comment]
@Angelicvorian Thanks for that input. I don't think this is the issue as the nodename and nodetype are not identical.

The version number is: 6.0.232.9494

**Comment by gkhanna79** [comment]
@justinoverton I presume you have already tried guidelines at https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-windows-cluster-windows-security and thus, ran into the issues above?

**Comment by originalnoe-nazvanie** [comment]
@justinoverton we have a checklist that you can easily convert to script
1) you should install gMSA account on your new node
`Add-WindowsFeature RSAT-AD-PowerShell
Add-LocalGroupMember -Group "Administrators" -Member "domain\gmsaSF$", "domain\SFadmins"
Install-ADServiceAccount gmsasf`

2) if your service fabric node is virtual machine and you want to use containers you should set some properties for nested virtualization and mac address spoofing(spoofing is not required now because service fabric currently use only NAT, there is no transparent network, but in future who knows). Virtual Machine should be stopped at the moment
`Set-VMProcessor -VMName sv51-sf -ExposeVirtualizationExtensions $true
Set-VMNetworkAdapter -VMName mv51-sf –VMNetworkAdapterName "Network Adapter" -MacAddressSpoofing On`

3) you should install required features such as hyper-v if you want to use docker containers on service fabric machine
`Install-WindowsFeature -Name hyper-v,containers,rdc -IncludeManagementTools -Restart
$activeadapters = Get-NetAdapter | Where-Object Status -EQ Up
New-VMSwitch –Name sf –NetAdapterName  $activeadapters.name
Install-PackageProvider -Name Nuget -MinimumVersion 2.8.5.201 -Force
Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
Install-Package -Name docker -ProviderName DockerMsftProvider -Confirm:$False -Force`

3) If you use certificates for inter-cluster communication for example you should install them on new node including private key
$Encrypted = convertto-securestring youpasswordcert -asplaintext -force
Import-PfxCertificate -Filepath 'D:\tmp\sf.travelline.wan.pfx' -password $Encrypted -CertStoreLocation Cert:\LocalMachine\My

4) You should check your local group policy settings such as "Run as a service" to ensure that local "Administrators" group is allowed to run as a service.
Usually we add "Run as a batch job" permission as well. Windows server default settings aloow local "Administrators" group to perform these tasks

5) You should chack that service fabric data directories presents on new machine and are located on NTFS volume
For example we use D volume for them and we create these directories
Part of cluster manifest:
`   "FabricSettings": [
     {
       "Name": "Setup",
       "Parameters": [
         {
           "Name": "FabricDataRoot",
           "Value": "D:\\SF"
         },
         {
           "Name": "FabricLogRoot",
           "Value": "D:\\SF\\Logs"
         }
       ]
     },`

Creating data directories
`New-Item -Type Directory -Path D:\SF
New-Item -Type Directory -Path D:\SF\Logs`


6) For convinience you can pull some images before you will use containers (if you will)
`docker pull microsoft/windowsservercore
docker pull microsoft/nanoserver`

7) Than on old service fabric node you should get current cluster manifest
`Connect-ServiceFabricCluster
Get-ServiceFabricClusterConfiguration >> c:\old.json`

Change it - add the new node to nodes section, save new config as
c:\new.json for example

test new configuration with TestConfiguration.ps1 script that is included to 
Microsoft.Azure.ServiceFabric.WindowsServer.6.1.480.9494 (any version sdk standalone package)

8) upgrade your cluster using new config file with new node 
`Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath c:\new.json -MaxPercentUnhealthyApplications 20 -MaxPercentUnhealthyNodes 20`

**Comment by justinoverton** [comment]
@originalnoe-nazvanie The next time I add a node I will try this checklist.

I ended up adding the NetFwTypeLib library to a directory accessible to the service fabric process. The permissions issues seemed to be due to the node being added by the service fabric service (therefore the user adding the node was the user the upgrade service was running as).

I'm not sure that the above checklist would have addressed any of the permissions issues I ran into with the gMSA account not having remote access to the registry.

**Comment by Angelicvorian** [comment]
Just thought i'd update this. Been performing some other testing which means re-visiting the Ansible module that performs all this for us.
I've found that by placing some constraints on where the RepairManager service is located and by using -MaxPercentUnhealthyNodes 13 -MaxPercentDeltaUnhealthyNodes 13 (percentage calculated from number of nodes to remove from the cluster and rounded up) switches on the upgrade-cluster command, I can get a gMSA based host to successfully remove itself from the cluster. 
This is only working with Non-SeedNode machines, as the placement constraints ensure repair manager is on SeedNodes only.
I've not yet tested it against SeedNodes, but i suspect the issue with removal is still there.

example of placement constraints from json config:
                 "addonFeatures": [
			"RepairManager"
		],
		"fabricSettings": [
			{
				"name": "Setup",
				"parameters": [
					{
						"name": "FabricDataRoot",
						"value": "C:\\ServiceFabricData\\SF"
					},
					{
						"name": "FabricLogRoot",
						"value": "E:\\ServiceFabricData\\SF\\Log"
					}
				]
			},
			{
				"name": "RepairManager",
				"parameters": [
					{
						"name": "EnableHealthChecks",
						"value": "true"
					},
					{
						"name": "MinReplicaSetSize",
						"value": "3"
					},
					{
						"name": "TargetReplicaSetSize",
						"value": "5"
					},
					{
						"name": "PlacementConstraints",
						"value": "NodeTypeName == SeedNode"
					}
				]
			}
		]

**Comment by maburlik** [comment]
There have been a few issues fixed in this area since the original post in 2018 such as an issue related to opening a named pipe to enable querying the remote machine registry, which appears to be the component hitting failure here. This along with other improvements should have made the experience smoother. Additionally, further improvements will be introduced as of 7.2 around the upgrade process to more clearly identify blocking issues. Feel free to open another thread if you are still hitting issues.

**Comment by vdvarlamov** [comment]
On cluster 7.2.413.9590, the problem persists!
