### ISSUE TITLE
Failing to enable BackupRestore service on standalone cluster with non en-us culture

### ISSUE THREAD

**Issue by b47on** [Microsoft/service-fabric#263]
I wanted to add the BackupRestore system service to my freshly upgraded (to 6.4) cluster on premises.

I followed the instructions (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-backuprestoreservice-quickstart-standalonecluster) and added this section to the cluster configuration:

```
        "addonFeatures": ["BackupRestoreService"],
        "fabricSettings": [
            {
                "name": "BackupRestoreService",
                "parameters":  [
                    {
                        "name": "SecretEncryptionCertThumbprint",
                        "value": "398C7279CAEF57948E58AF6C3E779E47F08D6B12"
                    }
                ]
            }
```
It worked for the local dev cluster but failed miserably on 3 nodes test cluster. The BackupRestore service crashes instantly with following errors being logged:

```
Failed to open store '' at LocalMachine: E_INVALIDARG
Failed to get the Certificate's private key. Thumbprint:398C7279CAEF57948E58AF6C3E779E47F08D6B12. Error: E_INVALIDARG
Failed to get private key file. x509FindValue: 398C7279CAEF57948E58AF6C3E779E47F08D6B12, x509StoreName: , findType: FindByThumbprint, Error E_INVALIDARG
```

Then 3 warnings are logged:

```
SetCertificateAcls failed. ErrorCode: E_INVALIDARG
Can't ACL BackupRestoreService/SecretEncryptionCertThumbprint, ErrorCode E_INVALIDARG
Error at AclConfiguredCertificates, ErrorCode E_FAIL
```

It looks like I were supposed to configure the store name, but the documentation does not mention any way to do that.

The application log if flooded with such entries:

```
Application: FabricBRS.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: RunAsync failed due to an unhandled exception causing the host process to crash: System.TypeInitializationException: The type initializer for 'System.Fabric.BackupRestore.Common.Constants' threw an exception. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Fabric.BackupRestore.Common.Constants.GetRuntimeVersion()
   at System.Fabric.BackupRestore.Common.Constants..cctor()
   --- End of inner exception stack trace ---
   at System.Fabric.BackupRestore.Common.BaseStore`2..ctor(IReliableDictionary`2 reliableDictionary, StatefulService statefulService, String traceType)
   at System.Fabric.BackupRestore.Common.WorkItemStore.<CreateOrGetWorkItemStore>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.BackupRestore.Common.BaseWorkItemQueue..ctor(IReliableQueue`1 workItemReliableQueue, Int32 maxWaitTimeInMinutes, WorkItemQueueRunType workItemQueueRunType, String traceType, StatefulService statefulService)
   at System.Fabric.BackupRestore.Common.WorkItemQueue.<CreateOrGetWorkItemQueue>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.BackupRestore.Common.WorkItemHandler.<StartAndScheduleWorkItemHandler>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.BackupRestore.Service.BackupRestoreService.<RunAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.<ExecuteRunAsync>d__23.MoveNext()
Stack:
   at System.Environment.FailFast(System.String)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

I want to add, that I have successfuly used the configured certificate to decrypt secrets in an application deployed to that cluster.

And I checked using powershell, that the certificate's private key ACL has been configured for NETWORK SERVICE:

Access : NT AUTHORITY\SYSTEM Allow  FullControl
         NT AUTHORITY\NETWORK SERVICE Allow  FullControl
         BUILTIN\Administrators Allow  FullControl

Any ideas?

**Comment by khandelwalbrijeshiitr** [comment]
@b47on, What is the default language of the machine??
Can you run this C# below code in the same machine and paste the o/p??
        CultureInfo ci = CultureInfo.InstalledUICulture;
        Console.WriteLine("* Name: {0}", ci.Name);

**Comment by raunakpandya** [comment]
So assuming all your machines are using English locale, does this repro for you consistently? I mean, what happens after failover or something?

**Comment by b47on** [comment]
I did further investigation, and InstalledUICulture is en-US but CultureInfo.CurrentCulture returns pl-PL - both using PowerShell remoting and calling it inside fabric app (as NETWORK SERVICE). 

And it is consistently failing, dumping FabricBRS.exe.*.dmp files in diagnostic store. I also tried on single node standalone clustere (also VM with same os and culture settings) - the same result.

**Comment by raunakpandya** [comment]
Thanks.. Seems like an issue parsing double in a machine which is in different culture. We are validating that and find ways to roll out the fix soon. As a mitigation for now, would it be possible for you to try it on a en-us build?

**Comment by b47on** [comment]
OK, I've tested it on a server with en-us Culture. Well, the BR service stopped crashing and generating the dumps, but it still cannot start - it keeps logging the first logs mentioned in my post - so there is still problem accessing the private key of the certificate...

**Comment by raunakpandya** [comment]
Logging of the empty store can be ignored. Are you running this with gMSA security? If so there is a known issue - #267 which you may wanna take a look. 

Also ensure that you don't pass more than 24 days for retention duration. Currently there is a known issue with that.

**Comment by raunakpandya** [comment]
You can ignore the errors which are getting logged for failing to get the private key. As long as you have configured the certificate for access to cluster yourself during setup this should be all fine. So from your response seems like, the service is running fine and the cluster is healthy. 

To answer your questions:
a. Yes, BRS takes a port from the application endpoint range. It may or may not be the first port but given this is one of the first services getting activated, it generally is the first port. 
b. No. This service is reachable via Gateway only.
c. The traffic from HTTP client to Gateway is encrypted using the server cert. Depending on your setup, the cluster/ server cert may or may not be same. 
d. Yes. Like any other SF APIs, you need admin cert for read/ write access and a non admin cert would just give you read access.

**Comment by raunakpandya** [comment]
This has been fixed in the latest refresh - https://blogs.msdn.microsoft.com/azureservicefabric/2019/02/04/azure-service-fabric-6-4-refresh-release/

**Comment by lanfeust69** [comment]
A somewhat related issue : Azure/service-fabric-issues#1553.
