### ISSUE TITLE
504 Server Error: FABRIC_E_TIMEOUT error

### ISSUE THREAD

**Issue by alexey-belous** [Microsoft/service-fabric#291]
I have 504 Server Error: FABRIC_E_TIMEOUT error during execution of `sfctl application upload` with Dockerized SF cluster. It happens when I'm uploading about 170 files, the error occurs when the most part of files is uploaded. `docker logs` doesn't show any errors in the logs.

Here is a full stack trace of `sfctl` utility:
```
504 Server Error: FABRIC_E_TIMEOUT for url: http://localhost:19080/ImageStore/publish/ProjectName/Code/publish/ProjectName.ApiPkg/Code/publish/_.dir?api-version=6.1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/usr/local/lib/python3.6/site-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/usr/local/lib/python3.6/site-packages/sfctl/custom_app.py", line 154, in upload
    show_progress)
  File "/usr/local/lib/python3.6/site-packages/sfctl/custom_app.py", line 116, in upload_to_native_imagestore
    res.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: FABRIC_E_TIMEOUT for url: http://localhost:19080/ImageStore/publish/JPI.Cloud.IdentityPkg/Code/publish/JPI.Cloud.Identity.ApiPkg/Code/publish/_.dir?api-version=6.1
```

Versions:
Service Fabric image: 6.4.625
sfctl: 6.0.0
Python: (Darwin) 3.6.5 (default, Nov 12 2018, 12:58:43)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]

**Comment by eihctir** [comment]
I too am having this same issue with the docker service fabric cluster. I am trying to upload a 400 plus file build output for aspnet core app.

**Comment by alexey-belous** [comment]
When timeout is occurred Service Fabric explorer shows this error in the ImageStoreService:
```
Unhealthy event: SourceId='System.CRM', Property='ReplicaConstraintViolation_Affinity', HealthState='Warning', ConsiderWarningAsError=false.
The Cluster Resource Manager has detected a Constraint Violation for this Replica:fabric:/System/ImageStoreService Secondary Partition 00000000-0000-0000-0000-000000003000 is violating the Constraint: Aligned Affinity true, Parent Service ClusterManagerServiceName 
 Parent PartitionId 00000000-0000-0000-0000-000000002000 
 Parent/Child ReplicaCounts 3/3 
 Parent Nodes: Node cf68563e16a44f808e86197a9cf83de5, N0020, Node b9d52c016a15a8f57673d3b8041e2d35, N0030, Node c2e9eff19761acc9924422c53c8943d0, N0010,  
 Child Nodes: Node c2e9eff19761acc9924422c53c8943d0, N0010, Node cf68563e16a44f808e86197a9cf83de5, N0020,
```

**Comment by iyyappam** [comment]
@alexey-belous, Thanks for filing the issue. We will take a look and update you.

**Comment by Christina-Kang** [comment]
Hi @alexey-belous, @eihctir, thank you for reporting the issue. 

@alexey-belous To help us debug, can you provide the cluster traces for your cluster? It should be located at `etc/servicefabric/FabricDataRoot` and an approximate time of when you ran the command? Can you also share the full command you ran and the output of the command with the --show-progress and --debug options? Do you know if any files are uploaded successfully / if the command always fails at the same area? The --show-progress option will tell you which files have already been uploaded. And one a side note, while this should not affect this particular scenario, for Service Fabric run time 6.4, you should have sfctl 7.x.x for best results. Most scenarios should be compatible, but there may have been breaking changes. Thank you!

@eihctir I suspect for your issue, the timeout is happening because the file being uploaded is too large for the timeout duration given by default. Do you know if it always fails at the same file? Right now, we don't have a good method to increase the timeout through the command line (this will be fixed in an upcoming release), but we can provide a custom build with this fix in the mean time. Which version of sfctl are you using? Can you also share the exact command you are using to upload? Thank you!

**Comment by eihctir** [comment]
@Christina-Kang are you saying because I have too many files or because a single file is too large? My largest file is 13MB. From what I can see it fails on different files.

I am using the install.sh bash script included with the linux template. 

`#!/bin/bash
cd `dirname $0`
sfctl application upload --path SampleApp --show-progress
sfctl application provision --application-type-build-path SampleApp
sfctl application create --app-name fabric:/SampleApp --app-type SampleAppType --app-version 1.0.0
cd -`

How do I see the cli version I have installed?

**Comment by alexey-belous** [comment]
@Christina-Kang, here's info that you asked:
1. Cluster traces are available here (from `/home/ClusterDeployer/ClusterData/Data/log/Traces`): https://drive.google.com/open?id=1yz7PPZPdwL4a-LdaZVWUSCH8JNJh9J5t


2. Command that I run is `sfctl application upload --path ./publish --show-progress --debug` (at 08:41 UTC) and the output is:
According to your recommendation I've upgraded `sfctl` to 7.0.0 version.
<details><summary>sfctl output:</summary>
<p>

```
[74/172] files, PROJECT_NAMEPkg/Code/wwwroot/lib/bootstrap/fonts/glyphicons-halflings-regular.woff
urllib3.connectionpool : http://localhost:19080 "PUT /ImageStore/publish/PROJECT_NAMEPkg/Code/wwwroot/lib/bootstrap/fonts/glyphicons-halflings-regular.eot?api-version=6.1 HTTP/1.1" 200 0
[75/172] files, PROJECT_NAMEPkg/Code/wwwroot/lib/bootstrap/fonts/glyphicons-halflings-regular.eot
urllib3.connectionpool : http://localhost:19080 "PUT /ImageStore/publish/PROJECT_NAMEPkg/Code/wwwroot/lib/bootstrap/fonts/glyphicons-halflings-regular.woff2?api-version=6.1 HTTP/1.1" 504 70
504 Server Error: FABRIC_E_TIMEOUT for url: http://localhost:19080/ImageStore/publish/PROJECT_NAMEPkg/Code/wwwroot/lib/bootstrap/fonts/glyphicons-halflings-regular.woff2?api-version=6.1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/site-packages/knack/invocation.py", line 188, in execute
    cmd_result = parsed_args.func(params)
  File "/usr/local/lib/python3.6/site-packages/knack/commands.py", line 105, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/knack/commands.py", line 212, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/usr/local/lib/python3.6/site-packages/sfctl/custom_app.py", line 154, in upload
    show_progress)
  File "/usr/local/lib/python3.6/site-packages/sfctl/custom_app.py", line 102, in upload_to_native_imagestore
    res.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: FABRIC_E_TIMEOUT for url: http://localhost:19080/ImageStore/publish/PROJECT_NAMEPkg/Code/wwwroot/lib/bootstrap/fonts/glyphicons-halflings-regular.woff2?api-version=6.1
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
Performing cluster version check
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
Check cluster version failed due to error: <class 'OSError'>
```
</p>
</details>


74 files of 172 are uploaded successfully (`find` utility also finds uploaded files in the container). 
Uploading process fails on random file each time, but sometimes it finished successfully.

Thanks for your help!

**Comment by Christina-Kang** [comment]
@alexey-belous, thanks for sharing the information! It looks like traces from 8:41 are not included in the traces shared (which end at 8:37). This could happen if you grabbed the traces right after running the command, and it hasn't been added to the trace file yet. If you haven't deleted the cluster, the traces will definitely be there now.  

Since it's failing on different files, and since it succeeds sometimes, it's most likely just a transient issue that should be retried. In a few business days, we expect to be publishing an update for sfctl which will include a fix for this (or be able to provide a private build here).

What are the sizes of files that upload is failing on?

Thanks!

**Comment by eihctir** [comment]
Sorry I can't find the trace files. I think I will wait for the new version of the cli. I am able to develop on a windows machine for now.
