### ISSUE TITLE
Installing standalone cluster fails: Not a cryptographic message or the cryptographic message is not formatted correctly. (Exception from HRESULT: 0x8009200D)

### ISSUE THREAD

**Issue by pregress** [Microsoft/service-fabric#292]
When installing a stand alone cluster based on the [docs](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server) we execute the following script:

`.\TestConfiguration.ps1 -ClusterConfigFilePath "ClusterConfig.Windows.OneNode.json" -FabricRuntimePackagePath "c:\temp\ServiceFabric\MicrosoftAzureServiceFabric.6.4.622.9590.cab"`

And we receive the following error:
```
Test Config failed with exception: System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: Not a cryptographic message or the cryptographic message is not formatted correctly. (Exception from HRESULT: 0x8009200D)
   at System.Fabric.Interop.NativeCommon.VerifyFileSignature(IntPtr filename, SByte& isValid)
   at System.Fabric.Common.FileSignatureVerifier.IsSignatureValid(String filename)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.CheckIsCabFile(String cabPath)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.AnalyzeClusterSetup(String configPath, String oldConfigPath, String cabPath, Boolean usingClusterManifest, FabricPackageType fabricPackageType, Boolean isForcedRun, Int32 maxPercentFailedNodes)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.<>c__DisplayClass1_0.<AnalyzeClusterSetupAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.BpaAnalyzeClusterSetup(String clusterConfigPath, String oldClusterConfigPath, String fabricPackagePath, Int32 maxPercentFailedNodes)
   at Microsoft.ServiceFabric.Powershell.ClusterCmdletBase.TestConfig(String clusterConfigPath, String oldClusterConfigPath, String fabricPackagePath, Int32 maxPercentFailedNodes)
   at Microsoft.ServiceFabric.Powershell.TestConfig.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
---> (Inner Exception #0) System.Runtime.InteropServices.COMException (0x8009200D): Not a cryptographic message or the cryptographic message is not formatted correctly. (Exception from HRESULT: 0x8009200D)
   at System.Fabric.Interop.NativeCommon.VerifyFileSignature(IntPtr filename, SByte& isValid)
   at System.Fabric.Common.FileSignatureVerifier.IsSignatureValid(String filename)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.CheckIsCabFile(String cabPath)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.AnalyzeClusterSetup(String configPath, String oldConfigPath, String cabPath, Boolean usingClusterManifest, FabricPackageType fabricPackageType, Boolean isForcedRun, Int32 maxPercentFailedNodes)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.<>c__DisplayClass1_0.<AnalyzeClusterSetupAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```
The server we execute this on, doesn't have internet connection. So we downloaded the file manually and put in in this location. 

The trace in DeploymentTraces contains the following:
```
2019/01/18-11:47:03.251,Info,1088,SystemFabricDeployer.SFDeployer,Running Best Practices Analyzer...
2019/01/18-11:47:03.251,Verbose,1088,SystemFabricDeployer.SFDeployer,Validating executing user is an Administrator.
2019/01/18-11:47:03.251,Verbose,1088,SystemFabricDeployer.SFDeployer,Converting JSON config to model.
2019/01/18-11:47:03.517,Info,1088,ImageBuilder.FabricDeployer,Host name: *******************$.
2019/01/18-11:47:03.533,Info,1088,ImageBuilder.FabricDeployer,Network interface ip address: f***********
2019/01/18-11:47:03.533,Info,1088,ImageBuilder.FabricDeployer,Network interface ip address: 172.16.250.20.
2019/01/18-11:47:03.533,Info,1088,ImageBuilder.FabricDeployer,Network interface ip address: ::1.
2019/01/18-11:47:03.533,Info,1088,ImageBuilder.FabricDeployer,Network interface ip address: 127.0.0.1.
2019/01/18-11:47:03.626,Verbose,1088,SystemFabricDeployer.SFDeployer,Validating CAB file is valid at c:\temp\ServiceFabric\MicrosoftAzureServiceFabric.6.4.622.9590.cab.

```

Additional logs are not created.

**Comment by pregress** [comment]
Redownloading the cab file worked.
