### ISSUE TITLE
Basic install of service fabric development doesn't work on Mac OS X and Ubuntu due to FileStoreService segfault

### ISSUE THREAD

**Issue by tastyeggs** [Microsoft/service-fabric#296]
I'm following the instructions to the dot, in getting a dev environment setup for service fabric on docker on Mac OS X. I got the cluster itself running, and my SF Dashboard looks OK.

However whenever I try to install a test reliable service application (generated by yeoman), the `./install.sh` fails when it tries to upload the application. At the same time, SF Dashboard reports that the ImageStoreService has experienced a quorum loss, and it fixes itself in a minute (I assume it experienced a crash).

I have the same error when trying this on Ubuntu (while still running the docker image).

Here's the error as reported on `./install.sh`:

```
user@instance-1:~/myapp/mystatefulapp$ ./install.sh 
[1/51] files, ApplicationManifest.xml
[2/51] files, _.dir
[3/51] files, MystatefulappservicePkg/ServiceManifest.xml
[4/51] files, MystatefulappservicePkg/_.dir
[5/51] files, MystatefulappservicePkg/Code/dotnet-include.sh
[6/51] files, MystatefulappservicePkg/Code/Mystatefulappservice.runtimeconfig.json
[7/51] files, MystatefulappservicePkg/Code/Mystatefulappservice.dll
[8/51] files, MystatefulappservicePkg/Code/Mystatefulappservice.deps.json
[9/51] files, MystatefulappservicePkg/Code/Mystatefulappservice.pdb
[10/51] files, MystatefulappservicePkg/Code/entryPoint.sh
[11/51] files, MystatefulappservicePkg/Code/_.dir
[12/51] files, MystatefulappservicePkg/Code/runtimes/_.dir
[13/51] files, MystatefulappservicePkg/Code/runtimes/win/_.dir
[14/51] files, MystatefulappservicePkg/Code/runtimes/win/lib/_.dir
[15/51] files, MystatefulappservicePkg/Code/runtimes/win/lib/netstandard2.0/Microsoft.ServiceFabric.Internal.Strings.dll
[16/51] files, MystatefulappservicePkg/Code/runtimes/win/lib/netstandard2.0/Microsoft.ServiceFabric.Diagnostics.dll
[17/51] files, MystatefulappservicePkg/Code/runtimes/win/lib/netstandard2.0/Microsoft.ServiceFabric.Data.Interfaces.dll
[18/51] files, MystatefulappservicePkg/Code/runtimes/win/lib/netstandard2.0/Microsoft.ServiceFabric.Data.Extensions.dll
[19/51] files, MystatefulappservicePkg/Code/runtimes/win/lib/netstandard2.0/System.Fabric.dll
[20/51] files, MystatefulappservicePkg/Code/runtimes/win/lib/netstandard2.0/Microsoft.ServiceFabric.ReliableCollection.Interop.dll
[21/51] files, MystatefulappservicePkg/Code/runtimes/win/lib/netstandard2.0/System.Fabric.Strings.dll
[22/51] files, MystatefulappservicePkg/Code/runtimes/win/lib/netstandard2.0/Microsoft.ServiceFabric.Data.dll
[23/51] files, MystatefulappservicePkg/Code/runtimes/win/lib/netstandard2.0/System.Fabric.Management.ServiceModel.dll
[24/51] files, MystatefulappservicePkg/Code/runtimes/win/lib/netstandard2.0/Microsoft.ServiceFabric.Services.dll
[25/51] files, MystatefulappservicePkg/Code/runtimes/win/lib/netstandard2.0/Microsoft.ServiceFabric.Internal.dll
[26/51] files, MystatefulappservicePkg/Code/runtimes/win/lib/netstandard2.0/Microsoft.ServiceFabric.Preview.dll
[27/51] files, MystatefulappservicePkg/Code/runtimes/win/lib/netstandard2.0/_.dir
[28/51] files, MystatefulappservicePkg/Code/runtimes/linux/_.dir
[29/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/_.dir
[30/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/System.Private.Interop.dll
[31/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/Microsoft.ServiceFabric.Internal.Strings.dll
[32/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/System.Private.CompilerServices.ICastable.dll
[33/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/Microsoft.ServiceFabric.Diagnostics.dll
[34/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/Microsoft.ServiceFabric.Data.Interfaces.dll
[35/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/Microsoft.ServiceFabric.Data.Extensions.dll
[36/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/System.Fabric.dll
[37/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/Microsoft.ServiceFabric.Internal.McgInterop.dll
[38/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/Microsoft.ServiceFabric.ReliableCollection.Interop.dll
[39/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/System.Fabric.Strings.dll
[40/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/Microsoft.ServiceFabric.Data.dll
[41/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/System.Fabric.Management.ServiceModel.dll
[42/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/Microsoft.ServiceFabric.Services.dll
[43/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/System.Fabric.McgInterop.dll
[44/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/Microsoft.ServiceFabric.Internal.dll
[45/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/Microsoft.ServiceFabric.Preview.dll
[46/51] files, MystatefulappservicePkg/Code/runtimes/linux/lib/netstandard2.0/_.dir
[47/51] files, MystatefulappservicePkg/Data/_readme.txt
[48/51] files, MystatefulappservicePkg/Data/_.dir
[49/51] files, MystatefulappservicePkg/Config/Settings.xml
[50/51] files, MystatefulappservicePkg/Config/_readme.txt
[51/51] files, MystatefulappservicePkg/Config/_.dir
Complete
(FABRIC_E_IMAGEBUILDER_VALIDATION_ERROR) Exception while parsing XML file: /home/ClusterDeployer/ClusterData/Data/N0020/Fabric/work/IB/131940845773649610/byhw4jzg.fge
FileName: /home/ClusterDeployer/ClusterData/Data/N0020/Fabric/work/IB/131940845773649610/byhw4jzg.fge --> InvalidOperationException: There is an error in XML document (0, 0). --> XmlException: Root element is missing.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.5/dist-packages/knack/invocation.py", line 188, in execute
    cmd_result = parsed_args.func(params)
  File "/usr/local/lib/python3.5/dist-packages/knack/commands.py", line 105, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/knack/commands.py", line 212, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/usr/local/lib/python3.5/dist-packages/sfctl/custom_app_type.py", line 120, in provision_application_type
    raise FabricErrorException(client._deserialize, response)
azure.servicefabric.models.fabric_error.FabricErrorException: (FABRIC_E_IMAGEBUILDER_VALIDATION_ERROR) Exception while parsing XML file: /home/ClusterDeployer/ClusterData/Data/N0020/Fabric/work/IB/131940845773649610/byhw4jzg.fge
FileName: /home/ClusterDeployer/ClusterData/Data/N0020/Fabric/work/IB/131940845773649610/byhw4jzg.fge --> InvalidOperationException: There is an error in XML document (0, 0). --> XmlException: Root element is missing.
(FABRIC_E_APPLICATION_TYPE_NOT_FOUND) Application type and version not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.5/dist-packages/knack/invocation.py", line 188, in execute
    cmd_result = parsed_args.func(params)
  File "/usr/local/lib/python3.5/dist-packages/knack/commands.py", line 105, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/knack/commands.py", line 212, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/usr/local/lib/python3.5/dist-packages/sfctl/custom_app.py", line 259, in create
    client.create_application(app_desc, timeout)
  File "/usr/local/lib/python3.5/dist-packages/azure/servicefabric/service_fabric_client_ap_is.py", line 3364, in create_application
    raise models.FabricErrorException(self._deserialize, response)
azure.servicefabric.models.fabric_error_py3.FabricErrorException: (FABRIC_E_APPLICATION_TYPE_NOT_FOUND) Application type and version not found
/home/user/myapp/mystatefulapp
```

**UPDATE:**
I'm encountering the exact same issue on a native Ubuntu 16.04 install. Upon further investigation, there appears to be a segfault on FileStoreService in /var/log/syslog:

```
Feb  8 22:50:45 fabric-ubuntu-dev kernel: [ 1665.850759] FileStoreServic[32657]: segfault at fffffffffffffff8 ip 00000000025fc4b7 sp 00007f06f1bfa6f0 error 7 in FileStoreService.exe[400000+3264000]
```
Did something break in a recent version?

Is there anyone using SF on linux/macOS for development?

**Comment by tastyeggs** [comment]
Ah, it looks like a rssh security issue for which you guys had sent out the advisory. Downgrading rssh fixes the issue.

https://blogs.msdn.microsoft.com/azureservicefabric/2019/02/07/known-issue-for-service-fabric-linux-clusters/
