### ISSUE TITLE
EventStoreService failing to install on Standalone cluster

### ISSUE THREAD

**Issue by cdonovan63** [microsoft/service-fabric#309]
Attempted to do both a clean install and an upgrade install of the EventStoreService on a Standalone service fabric cluster.  We are using "Windows" credential types fro both "ClusterCredentialType" and "ServerCredentialType".  Our cluster is using a "ClustergMSAIdenity.

When the cluster starts up the EventStore Service has the following error:

> 'System.RA' reported Warning for property 'ReplicaOpenStatus'. Replica had multiple failures during open on vm4. API call: IStatefulServiceReplica.ChangeRole(P);
Error = System.Reflection.TargetInvocationException (-2146232828) Exception has been thrown 
by the target of an invocation.
System.Net.HttpListenerException (-2147467259)
Access is denied
    at System.Net.HttpListener.AddAllPrefixes() 
   at System.Net.HttpListener.Start()
    at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 
        appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
    at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 
       properties)
--- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature 
        sig, Boolean constructor)
    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] 
       parameters, Object[] arguments)
    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder 
        binder, Object[] parameters, CultureInfo culture)
    at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
    at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
    at EventStore.Service.ApiEndpoints.Server.OwinHttpServer.StartOwinHttpServer(String 
        listenAddress)
    at EventStore.Service.ApiEndpoints.Server.OwinCommunicationListener.OpenAsync(CancellationToken cancellationToken)
    at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.d__18.MoveNext()
--

**Comment by mccw** [comment]
EventStoreService is not supported on standalone clusters yet.

**Comment by raunakpandya** [comment]
Closing the issue.
