### ISSUE TITLE
Event Store storage exception after cluster upgrade to 6.5

### ISSUE THREAD

**Issue by tuhland** [microsoft/service-fabric#358]
Our clusters recently upgraded to SF 6.5.

We never looked into Event Store before - chances are good it never actually worked, but now it's throwing errors in the Fabric Explorer.

Basically the Event Store service tries to connect to a wrong table connection and fails. Which leads to endless restarting on different nodes. 
We didn't configure a table connection so I assume it tried to configure itself automagically during the upgrade. 

It fails to connect to _**RESOURCENAME**.table.core.windows.net_, because it should be _**RESOURCENAME**.table.core.cloudapi.de_ instead.

This is the exception thrown on the VMs:

Application: EventStore.Service.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: Exception Type: System.AggregateException, Message: One or more errors occurred., Stack: Inner Exception DetailsException Type: Microsoft.WindowsAzure.Storage.StorageException, Message: The remote name could not be resolved: '**RESOURCENAME**.table.core.windows.net', Stack:    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Instrumentation.Tracing.Readers.AzureTableReader.AzureTableExtensions.<ExecuteTableQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Instrumentation.Tracing.Readers.AzureTableReader.AccountAndKeyTableStorageAccess.<ExecuteQueryAsyncInternal>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventStore.Service.Cache.DataFetcher`2.<FetchDataInternalAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventStore.Service.Cache.Cache`2.<InitHydrateAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventStore.Service.Cache.AzureTableCachedStorageAccess.<ExecuteCacheOpWithRetryAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventStore.Service.Cache.AzureTableCachedStorageAccess.<UpdateRegularlyAsync>d__33.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at EventStore.Service.TaskRunner+<>c__DisplayClass1_0+<<GetDefaultContinuation>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[[EventStore.Service.TaskRunner+<>c__DisplayClass1_0+<<GetDefaultContinuation>b__0>d, EventStore.Service, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<<GetDefaultContinuation>b__0>d ByRef)
   at EventStore.Service.TaskRunner+<>c__DisplayClass1_0.<GetDefaultContinuation>b__0(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by tuhland** [comment]
Some other strange behavior, we noticed since yesterday, which may be related to this:

- When we open the Fabric Explorer there's an error message stating that it couldn't get the cluster manifest, but everything seems to be working. I can even look at the manifest.
- After some time (probably more than an hour) I get logged out of the Fabric Explorer with Azure AD telling me it was due to an authentication loop. I will paste the exact message here when I get it again.

**Comment by KurtSunday** [comment]
We are having a very similar set of issues since starting to create our environments with Service Fabric version 6.5.641.9590.

Please post a solution if you have one.

**Comment by KurtSunday** [comment]
Possible reference material for the problem.

https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-breaking-changes

**Comment by tuhland** [comment]
I finally had time to try to fix this issue, but it's still here.

**Event Store Error**
I disabled the event store feature in the ARM template and updated the cluster, but the service was still there and throwing errors. This error message also still shows up everytime I open the explorer:
`Error: Get cluster manifest failed`


**Frequent Logout**
This issue still occurs, but very likely is not related to the Event Store stuff (as posted above by Kurt).
