### ISSUE TITLE
COMException: Error HRESULT E_FAIL has been returned from a call to a COM component in one service in 1Node mode

### ISSUE THREAD

**Issue by abatishchev** [microsoft/service-fabric#367]
Hi,
We're getting the following exception:

```
System.Fabric.FabricException: 'An error occurred during this operation.  Please check the trace logs for more details.'
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
   at System.Fabric.Interop.Utility.RunInMTA[TResult](Func`1 func)
   at MyProject.LoggerFactory.Initialize() in D:\Projects\My-Project\src\Applications\Common\IfxLogger\LoggerFactory.cs:line 47

Inner exception: COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Fabric.Interop.NativeRuntime.FabricGetActivationContext(Guid& riid)
   at System.Fabric.FabricRuntime.NativeFabricRuntimeFactory.GetCodePackageActivationContextHelper()
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
```

in a call to:

```c#
private static void Main()
{
   LoggerFactory.Initialize();
   ServiceRuntime.RegisterServiceAsync("MyFailingServiceType", context => new Gateway(context)).GetAwaiter().GetResult();
}

public class LoggerFactory
{
    public static void Initialize()
    {
        FabricRuntime.GetActivationContext()
    }
}
```

The problem is that:

- the exception occurs only in one out of 4 services, both stateful and stateless
- only locally when application is debugged from VS2019 via F5

Please assist us in troubleshooting this.

**Comment by abatishchev** [comment]
Hard to reproduce, no traction
