### ISSUE TITLE
Fatal error when running SF Docker container on Ubuntu 18.04

### ISSUE THREAD

**Issue by Feenposhleen** [microsoft/service-fabric#385]
Hello

I know that native 18.04 support is coming up, but for now I'm trying to get SF to run on my 18.04 machine using the Docker process described for macOS (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-mac). The container builds and sets up correctly, but when trying to run it, I get the following error:

```
Failed to retrieve node last boot up time exception System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.Fabric.FabricDeployer.Utility.GetNodeLastBootUpTimeFromSystem() in /var/build/workspace/ServiceFabric/Release_6.5_Ubuntu1604_Nightly/src/prod/src/managed/Api/src/System/Fabric/Management/fabricdeployer/Utility.cs:line 1289
Failed to retrieve node last boot up time exception System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.Fabric.FabricDeployer.Utility.GetNodeLastBootUpTimeFromSystem() in /var/build/workspace/ServiceFabric/Release_6.5_Ubuntu1604_Nightly/src/prod/src/managed/Api/src/System/Fabric/Management/fabricdeployer/Utility.cs:line 1289
Last boot up time from registry:01/01/0001 00:00:00 from system:01/01/0001 00:00:00
Skipping container network iptable set up because node has not been rebooted.
DockerDnsHelper current node IPAddressOrFQDN <>
Starting DockerDnsHelper.CleanupAsync
Executing DockerDnsHelper.CleanupAsync, attempt 1 of 3
Persisted network details cleaned up
Removing firewall rule WindowsFabric.Dns.v1 if it exists...
iptables v1.6.0: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
Error removing firewall rule WindowsFabric.Dns.v1. Ignoring and continuing. This must be cleaned up manually. Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NetFwTypeLib.NetFwRules.Remove(String name) in /var/build/workspace/ServiceFabric/Release_6.5_Ubuntu1604_Nightly/src/prod/src/managed/Api/CoreCLRDlls/System.Fabric.Management/src/NetFwRules.cs:line 153
   at System.Fabric.FabricDeployer.DockerDnsHelper.RemoveFirewallRule() in /var/build/workspace/ServiceFabric/Release_6.5_Ubuntu1604_Nightly/src/prod/src/managed/Api/src/System/Fabric/Management/fabricdeployer/DockerDnsHelper.cs:line 765
Successfully completed DockerDnsHelper.CleanupAsync
Completed DockerDnsHelper.CleanupAsync
Released writer lock on /home/ClusterDeployer/ClusterData/Data/lock
Starting FabricHost
Starting Fabric Host as console application.
IPC server open failed with 0x80070063
Failed to set certificate acls. Error: E_FAIL
```
Sorry if this is a known issue. I figured that since the process that's failing is inside the Docker container, it would fail regardless of which OS is the container host. 

Ubuntu 18.04 LTS
Docker 18.06

**Comment by ihildebrandt** [comment]
I had a similar issue to this. Make sure that you've applied the following settings to the Docker Daemon and restarted: 

```
{
    "ipv6": true,
    "fixed-cidr-v6": "fd00::/64"
}
```

Ref: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-mac

**Comment by Feenposhleen** [comment]
@ihildebrandt Thank you! I had actually made that change, but your comment made me think it didn't take. Turns out I had installed Docker using snap instead of apt. Because of this, the config file in question wasn't read. 

Reinstalled docker using apt, and it works fine now!
