### ISSUE TITLE
Unable to provision application due to FABRIC_E_IMAGEBUILDER_UNEXPECTED_ERROR on service fabric docker image using sfctl on Ubuntu 18.04

### ISSUE THREAD

**Issue by bryanegrahamfg** [microsoft/service-fabric#395]
Hey there!

We're seeing a strange deployment issue recently on some of our developer machines where we are unable to provision our application successfully on the service fabric docker image.

I've included a dump of information below, please let me know if there is anything else that you need, or if there is a specific template for reporting that I should follow.

# Environment
Pop_OS (18.04 derivative)

**Docker Version**"
Docker version 19.03.2, build 6a30dfc

**Service Fabric Env**
`6.5.466.1` from `mcr.microsoft.com/service-fabric/onebox`
(Dockerfile attached if relevant)

We're also been able to replicate with `microsoft/service-fabric-onebox` both `latest` and `6.3.124`

**sfctl version**
```
sfctl --version
8.0.0

Python (Linux) 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0]

Python location '/usr/bin/python3'

```
Have also replicated with sfctl 7.10

# Things I have tried
- Version dancing the docker image version and sfctl version.
- I have verified that all impacted machines can deploy to actual running clusters

# sfctl Logs
```
sfctl cluster select --endpoint http://localhost:19080 --verbose
Performing cluster version check
Check cluster version failed due to error: <class 'OSError'>
sfctl application upload --path ./FreshGradeApp.Cluster --show-progress --verbose
[1/13] files, 11.a
Time left: 300 seconds
[2/13] files, AA.a
Time left: 300 seconds
[3/13] files, app_name
Time left: 300 seconds
[4/13] files, Aa.a
Time left: 300 seconds
[5/13] files, aa.a
Time left: 299 seconds
[6/13] files, ApplicationManifest.xml
Time left: 299 seconds
[7/13] files, version
Time left: 299 seconds
[8/13] files, _.dir
Time left: 299 seconds
[9/13] files, FreshGradeApp.ClusterPkg/Data.zip
Time left: 297 seconds
[10/13] files, FreshGradeApp.ClusterPkg/Code.zip
Time left: 295 seconds
[11/13] files, FreshGradeApp.ClusterPkg/Config.zip
Time left: 295 seconds
[12/13] files, FreshGradeApp.ClusterPkg/ServiceManifest.xml
Time left: 295 seconds
[13/13] files, FreshGradeApp.ClusterPkg/_.dir
Time left: 294 seconds
Complete
sfctl application provision --application-type-build-path FreshGradeApp.Cluster --timeout 500 --debug
Command arguments: ['application', 'provision', '--application-type-build-path', 'FreshGradeApp.Cluster', '--timeout', '500', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fc571268bf8>, <function OutputProducer.on_global_arguments at 0x7fc570fb7730>, <function CLIQuery.on_global_arguments at 0x7fc570d45378>]
Event: CommandInvoker.OnPreCommandTableCreate []
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate []
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fc570fb77b8>, <function CLIQuery.handle_query_parameter at 0x7fc570d45400>]
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.service_client : Accept header absent and forced to application/json
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTP connection (1): localhost:19080
urllib3.connectionpool : http://localhost:19080 "POST /ApplicationTypes/$/Provision?api-version=6.2&timeout=500 HTTP/1.1" 500 116
msrest.exceptions : (FABRIC_E_IMAGEBUILDER_UNEXPECTED_ERROR) Value cannot be null.
Parameter name: path1
(FABRIC_E_IMAGEBUILDER_UNEXPECTED_ERROR) Value cannot be null.
Parameter name: path1
Traceback (most recent call last):
  File "/home/bryan/.local/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/bryan/.local/lib/python3.6/site-packages/sfctl/entry.py", line 81, in execute
    return super(SFInvoker, self).execute(args)
  File "/home/bryan/.local/lib/python3.6/site-packages/knack/invocation.py", line 188, in execute
    cmd_result = parsed_args.func(params)
  File "/home/bryan/.local/lib/python3.6/site-packages/knack/commands.py", line 105, in __call__
    return self.handler(*args, **kwargs)
  File "/home/bryan/.local/lib/python3.6/site-packages/knack/commands.py", line 212, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/home/bryan/.local/lib/python3.6/site-packages/sfctl/custom_app_type.py", line 117, in provision_application_type
    raise FabricErrorException(client._deserialize, response)
azure.servicefabric.models._models_py3.FabricErrorException: (FABRIC_E_IMAGEBUILDER_UNEXPECTED_ERROR) Value cannot be null.
Parameter name: path1
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
Performing cluster version check
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
Check cluster version failed due to error: <class 'OSError'>
```

[Dockerfile.zip](https://github.com/microsoft/service-fabric/files/3644744/Dockerfile.zip)

**Comment by maburlik** [comment]
@iyyappam, @Christina-Kang : Are we aware of scenarios that would result in:
(FABRIC_E_IMAGEBUILDER_UNEXPECTED_ERROR) Value cannot be null.

@bryanegrahamfg : Have you tried increasing the timeout?

**Comment by Christina-Kang** [comment]
@bryanegrahamfg do you have service fabric logs for when you get this error? Can you also provide the UTC timestamp of when this happened? If you have the info, please email it to me at bikang@microsoft.com I believe the logs should be in etc/servicefabric/FabricDataRoot
Thank you!

**Comment by bryanegrahamfg** [comment]
Thank you both for your replies.

@maburlik 
> @bryanegrahamfg : Have you tried increasing the timeout?

The timeout is set the 500s but it also dies almost instantly.
