### ISSUE TITLE
How to upload from xstore to fabric:imagestore?

### ISSUE THREAD

**Issue by sarahdonofrio** [microsoft/service-fabric#452]
Hi, I see there is an intentional block/check that does not allow an xstore cluster manifest to upgrade to a fabric:imagestore cluster manifest 
If we were historically using xstore and want to move to fabric:imagestore, is there some place we can check this is intentional and we want to make this change, or is it impossible to reprovision a cluster in the image store? 
More guidance around that error and how to change migrate to fabric:imagestore and use that service would be appreciated.
Thanks!

**Comment by sarahdonofrio** [comment]
For more context this is in regards to:
System.AggregateException: One or more errors occurred. ---> System.Fabric.FabricException: The upgrade is not allowed due to exception System.ArgumentException: the old image store connection string starts with xstore prefix but new one is not
   at System.Fabric.Management.WindowsFabricValidator.ManagementConfigurationValidators.WriteError(String format, Object[] args)
   at System.Fabric.Management.WindowsFabricValidator.ManagementConfigurationValidators.CompareImageStoreConnectionString(WindowsFabricSettings newWindowsFabricSettings)
   at System.Fabric.Management.WindowsFabricValidator.ManagementConfigurationValidators.ValidateConfigurationUpgrade(WindowsFabricSettings currentWindowsFabricSettings, WindowsFabricSettings targetWindowsFabricSettings)

**Comment by sarahdonofrio** [comment]
Ah I figured out the issue and propose the following update to the error messages:
        public bool CompareImageStoreConnectionString(WindowsFabricSettings newWindowsFabricSettings)
        {
            var oldImageStoreConnectionChars = FabricValidatorUtility.SecureStringToCharArray(this.ImageStoreConnectionString);
            var newImageStoreConnectionChars = FabricValidatorUtility.SecureStringToCharArray(
                newWindowsFabricSettings.GetParameter(
                this.SectionName,
                FabricValidatorConstants.ParameterNames.ImageStoreConnectionString).GetSecureValue(this.StoreName));

            if (FabricValidatorUtility.StartsWithIgnoreCase(oldImageStoreConnectionChars, FabricValidatorConstants.FileImageStoreConnectionStringPrefix))
            {
                if (!FabricValidatorUtility.StartsWithIgnoreCase(newImageStoreConnectionChars, FabricValidatorConstants.FileImageStoreConnectionStringPrefix))
                {
                    **WriteError("The old image store connection string starts with file prefix but new one does not. If this is intentional, set the parameter AllowImageStoreConnectionStringChange to true.");**
                    return false;
                }

                return CompareFileImageStoreConnectionString(new string(oldImageStoreConnectionChars), new string(newImageStoreConnectionChars));
            }
            else if (FabricValidatorUtility.StartsWithIgnoreCase(oldImageStoreConnectionChars, FabricValidatorConstants.XStoreImageStoreConnectionStringPrefix))
            {
                if (!FabricValidatorUtility.StartsWithIgnoreCase(newImageStoreConnectionChars, FabricValidatorConstants.XStoreImageStoreConnectionStringPrefix))
                {
                    **WriteError("The old image store connection string starts with xstore prefix but new one does not. If this is intentional, set the parameter AllowImageStoreConnectionStringChange to true.");**
                    return false;
                }

                return CompareXStoreImageStoreConnectionString(new string(oldImageStoreConnectionChars), new string(newImageStoreConnectionChars));
            }
            else if (FabricValidatorUtility.StartsWithIgnoreCase(oldImageStoreConnectionChars, FabricValidatorConstants.FabricImageStoreConnectionStringPrefix))
            {
                if (!FabricValidatorUtility.StartsWithIgnoreCase(newImageStoreConnectionChars, FabricValidatorConstants.FabricImageStoreConnectionStringPrefix))
                {
                    **WriteError("The old image store connection string starts with fabric prefix but new one is notdoes not. If this is intentional, set the parameter AllowImageStoreConnectionStringChange to true");**
                    return false;
                }

                return CompareFabricImageStoreConnectionString(new string(oldImageStoreConnectionChars), new string(newImageStoreConnectionChars));
            }
            else if (FabricValidatorUtility.StartsWithIgnoreCase(oldImageStoreConnectionChars, FabricValidatorConstants.DefaultTag))
            {
                if (!FabricValidatorUtility.StartsWithIgnoreCase(newImageStoreConnectionChars, FabricValidatorConstants.DefaultTag))
                {
                    **WriteError("The old image store connection string starts with default prefix but new one is notdoes not. If this is intentional, set the parameter AllowImageStoreConnectionStringChange to true");**
                    return false;
                }
                return true;
            }
            else
            {
                WriteError(
                    "Value for section {0} parameter {1} should start with {2}, {3} or {4}",
                    this.SectionName,
                    FabricValidatorConstants.ParameterNames.ImageStoreConnectionString,
                    FabricValidatorConstants.XStoreImageStoreConnectionStringPrefix,
                    FabricValidatorConstants.FileImageStoreConnectionStringPrefix,
                    FabricValidatorConstants.FabricImageStoreConnectionStringPrefix);
                return false;
            }
        }
