### ISSUE TITLE
FabActUtil - Could not load type 'System.Collections.ArrayList' from assembly 'netstandard, Version=2.1.0.0

### ISSUE THREAD

**Issue by pregress** [microsoft/service-fabric#455]
The following error occurs when building inside Visual Studio 2019, or building with cli. 

```
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  ***** -> C:\dev\*****\*****\src\*****Actor\*****\bin\Debug\netcoreapp3.1\win7-x64\*****.dll

  Unhandled Exception: System.TypeLoadException: Could not load type 'System.Collections.ArrayList' from assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
     at FabActUtil.CommandLineParser.CommandLineArgumentParser..ctor(Type argumentSpecification, ErrorReporter reporter)
     at FabActUtil.CommandLineParser.CommandLineUtility.ParseCommandLineArguments(String[] arguments, Object destination, ErrorReporter reporter)
     at FabActUtil.Program.Main(String[] args)
C:\Users\*****\.nuget\packages\microsoft.servicefabric.actors\4.0.470\build\netcoreapp2.0\Microsoft.ServiceFabric.Actors.targets(26,5): error MSB3073: The command "dotnet "obj\\FabActUtilTemp\FabActUtil.dll" /spp:"PackageRoot" /t:manifest /sp:"*****" /in:"bin\Debug\netcoreapp3.1\win7-x64\\*****.dll" /arp:"C:\dev\*****\*****\src\*****Actor\*****\bin\Debug\netcoreapp3.1\win7-x64\\" /smep:Exe " exited with code -532462766. [C:\dev\*****\*****\src\*****Actor\*****\*****.csproj]

Build FAILED.
```

Versions:

- MsBuild : 16.4.0+e901037fe
- dotnet core: 3.1.101
- Service Fabric SDK: 4.0.470
- Windows: 1903 (OS Build 18362.657)

When I look in the obj\\FabActUtilTemp folder at the netstandard.dll the product version is 3.1.0 while FabActUtil is trying to resolve 2.1.0

Any Idea on how to solve this?

**Comment by BigMorty** [comment]
Assigning this to @dbreshears who can have someone take a closer look.

**Comment by dbreshears** [comment]
@anantshankar17, can you help look into?

**Comment by pregress** [comment]
Are you able to reproduce it? 
Do you need the full build log ?

**Comment by dbreshears** [comment]
@pregress, 

Does this reproduce with a new project using the default Actor template?  

I haven't been able to reproduce with 4.0.470 SDK installed and the same version of the Actor NuGet package referenced.  I do have a later dotnet core though.   I don't recall ever seeing this error with previous .Net Core versions though with our testing. The product version in FabActUtilTemp will show 3.1 but my assembly version is 2.1 (inspecting with ildasm) so I don't think that is the issue, but you can verify in your folder.

Which VS version 2019 are you on?   
Sharing detailed msbuild log may help or if you have any additional references or custom settings to the Actor or Actor.Interfaces projects.

**Comment by pregress** [comment]
Visual studio 2019  (16.3.7)

When trying to reproduce it in a new solution, the problem didn't occur.

I was able to solve the problem:

- Remove the existing actor from the solution. 
- Create a new Actor via the Wizard on the services in sfproj 
- Copied all existing code into the folders
- Update the .csproj files with the required references.
- Changed the ServiceManifest and Application manifest with the required EnvironmentVaraibles

build and run now 

If required I can still share the original detailed build output when it was failing. 
Otherwise this can be closed

**Comment by hanxinimm** [comment]
3>
3>Unhandled Exception: System.TypeLoadException: Could not load type 'System.Collections.ArrayList' from assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
3>   at FabActUtil.CommandLineParser.CommandLineArgumentParser..ctor(Type argumentSpecification, ErrorReporter reporter)
3>   at FabActUtil.CommandLineParser.CommandLineUtility.ParseCommandLineArguments(String[] arguments, Object destination, ErrorReporter reporter)
3>   at FabActUtil.Program.Main(String[] args)
3>C:\Users\hanxi\.nuget\packages\microsoft.servicefabric.actors\4.1.417\build\netcoreapp2.0\Microsoft.ServiceFabric.Actors.targets(26,5): error MSB3073: 命令“dotnet "obj\\FabActUtilTemp\FabActUtil.dll" /spp:"PackageRoot" /t:manifest /sp:"IDCreatorActor" /in:"bin\Debug\netcoreapp3.1\win7-x64\\IDCreatorActor.dll" /arp:"D:\LaborDispatch\IDCreatorSF\IDCreatorActor\bin\Debug\netcoreapp3.1\win7-x64\\" /smep:Exe ”已退出，代码为 -532462766。
3>
