### ISSUE TITLE
UseImplicitHost=true in ServiceManifest.xml causes incorrect error: FABRIC_E_SERVICE_TYPE_ALREADY_REGISTERED?

### ISSUE THREAD

**Issue by abatishchev** [microsoft/service-fabric#462]
I'm converting a small application from a guest executable using a cmd script to SDK-dependent stateful service targeting .NET Core 3.1 using dotnet.exe. I'm having this line in its ServiceManifest.xml:

```xml
<StatelessServiceType ServiceTypeName="TestAgentInstallerType" UseImplicitHost="true" />
```

Here's its Program.cs:

```c#
internal static class Program
{
    public static async Task Main()
    {
        await ServiceRuntime.RegisterServiceAsync("TestAgentInstallerType", context => new TestAgentService(context));

        await Task.Delay(Timeout.Infinite);
    }
}

public class TestAgentService : StatefulService
{
    public TestAgentService(StatefulServiceContext context)
        : base(context)
    {
    }

    protected override Task RunAsync(CancellationToken cancellationToken) =>
        Task.CompletedTask;
}
```

and it throws exception at the very first line:

>System.Fabric.FabricException
  HResult=0x80071BD1
  Message=Service Type is already registered.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 151
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 107
   at Microsoft.ServiceFabric.Services.Runtime.ServiceRuntime.<RegisterServiceAsync>d__1.MoveNext()

`0x80071BD1` corresponds to `FABRIC_E_SERVICE_TYPE_ALREADY_REGISTERED`. What is not true.

If I remove this attribute from the manifest then the code runs but the process is getting terminated within about a minute:

>The program '[11376] dotnet.exe' has exited with code -1073741510 (0xc000013a).
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[15404] cmd.exe' has exited with code 0 (0x0).

**Comment by abatishchev** [comment]
It's either `UseImplicitHost="true"` of `dotnet run`, not both.
