### ISSUE TITLE
IStatefulServiceReplica.Open(); Error = System.NotSupportedException

### ISSUE THREAD

**Issue by veertien** [microsoft/service-fabric#485]
On my 1-node development cluster, I get this error when my sateful service is deployed and then I rebuild the project in Visual Studio.

## Expected Behavior

The service should restart without an exception

## Current Behavior

Service goes into error state with:

```
'System.RA' reported Warning for property 'ReplicaOpenStatus'.
Replica had multiple failures during open on _Node_0. API call: IStatefulServiceReplica.Open(); Error = System.NotSupportedException (-2146233067)
Specified method is not supported.
   at Microsoft.ServiceFabric.Replicator.RecoveryManager.PerformRecoveryAsync(RecoveredOrCopiedCheckpointLsn recoveredOrCopiedCheckpointLsn, OperationProcessor recordsProcessor, CheckpointManager checkpointManager, TransactionManager transactionManager, LogRecordsDispatcher logRecordsDispatcher, ReplicatedLogManager replicatedLogManager)
   at Microsoft.ServiceFabric.Replicator.LoggingReplicator.PerformRecoveryAsync(RecoveryInformation recoveryInformation)
   at Microsoft.ServiceFabric.Replicator.DynamicStateManager.OpenAsync(ReplicaOpenMode openMode, TransactionalReplicatorSettings transactionalReplicatorSettings)
   at Microsoft.ServiceFabric.Replicator.TransactionalReplicator.OpenAsync(ReplicaOpenMode openMode, TransactionalReplicatorSettings transactionalReplicatorSettings)
   at Microsoft.ServiceFabric.Replicator.StatefulServiceReplica.System.Fabric.IStatefulServiceReplica.OpenAsync(ReplicaOpenMode openMode, IStatefulServicePartition partitionObject, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Data.ReliableStateManagerImpl.Microsoft.ServiceFabric.Data.IStateProviderReplica.OpenAsync(ReplicaOpenMode openMode, IStatefulServicePartition partition, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.System.Fabric.IStatefulServiceReplica.OpenAsync(ReplicaOpenMode openMode, IStatefulServicePartition partition, CancellationToken cancellationToken)
For more information see: <a href='https://aka.ms/sfhealth' target='_blank'>https://aka.ms/sfhealth</a>

```

## Steps to Reproduce

1. Deploy the stateful service to local 1-node cluster
2. In Visual Studio, rebuild the stateful service project

#### Service Fabric Runtime and SDK Version :

* SDK: 4.0.470.9590
* Runtime: 7.0.470.9590

#### Operating System :
Windows 10

#### Cluster Size :
1-node dev box

**Comment by woeterman94** [comment]
Any update / fix for this?
