### ISSUE TITLE
Mounting a host folder inside a container fails deployment

### ISSUE THREAD

**Issue by gheibia** [microsoft/service-fabric#535]
I'm trying to mount a host folder to a containerized application deployed on Service Fabric. In the "ApplicationManifest.xml" I have something like this:

```
<ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="MyAppPkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides />
    <Policies>
      <ContainerHostPolicies CodePackageRef="Code">
        <Volume Source="d:\hostfolder" Destination="c:\container" IsReadOnly="false" />
      </ContainerHostPolicies>
    </Policies>
  </ServiceManifestImport>
```

I'm testing this with a local cluster on my dev machine.

If I don't create `d:\hostfolder` on my machine, I get a `FABRIC_E_DIRECTORY_NOT_FOUND` deployment error (obviously). If do, the deployment fails with `'System.RAP' reported Warning for property 'IStatelessServiceInstance.OpenDuration'. The api IStatelessServiceInstance.Open on node _Node_0 is stuck.`

Running `docker ps -a` I can see the container is created, but never activated.
And looking at the cluster's logs, I see the following entries:

```
Finish IStatelessServiceInstance.Open() on node bf865279ba277deb864a976fbf4c200e:132176268775856915(_Node_0) on partition {0aefe61a-635b-4541-816e-5634bbc94972} replica 132176272992839885. ServiceType = MyAppType. Elapsed = 240000.8918ms. Error = FABRIC_E_TIMEOUT. Message = 
```

AND

```
Failed to start Container. ContainerName=sf-0-340cf41f-8966-4f5f-9c32-0229f8296466_2a8b0780-f616-47c0-a00d-7e8aa871239d, ApplicationId=MyApp_SFCType_App0, ApplicationName=fabric:/myapp.System.Fabric.FabricException: Docker operation timed out. RequestUri=http://docker_engine/containers/sf-0-340cf41f-8966-4f5f-9c32-0229f8296466_2a8b0780-f616-47c0-a00d-7e8aa871239d/start
   at Microsoft.ServiceFabric.ContainerServiceClient.ContainerServiceClient.<MakeRequestPrivateAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.ContainerServiceClient.ContainerServiceClient.<MakeRequestAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.ContainerServiceClient.ContainerOperation.<StartContainerAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hosting.ContainerActivatorService.Utility.<>c__DisplayClass14_0.<<ExecuteWithRetryOnTimeoutAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hosting.ContainerActivatorService.Utility.<ExecuteWithRetryOnTimeoutAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hosting.ContainerActivatorService.ActivateContainerOperation.<StartContainerAsync>d__20.MoveNext()

```

I've restarted docker followed by removing and recreating the cluster. I'm not sure why docker times out activating the container. To be sure, I tested creating the container directly through docker with a new mount using `docker run -d -p 80:80 --isolation process --name myapp -v d:/hostfolder:c:/container myAppImage:local`.

**Comment by gheibia** [comment]
This no longer happens. I suspect either a docker upgrade or a cluster upgrade resolved the issue.
