### ISSUE TITLE
DNS Resolution failing with SocketException

### ISSUE THREAD

**Issue by ELymar** [microsoft/service-fabric#539]
Trying to debug DNS issues. I am running two services AnApi and AnotherApi. 
```
        [HttpGet]
        public async Task<string> Get()
        {
            string result = "";
            try
            {
                Uri uri = new Uri("http://anapi.debuggingdns:10556/api/values");
                var hostAddress = Dns.GetHostAddresses(uri.DnsSafeHost);
                Console.WriteLine(hostAddress);
                HttpClient client = new HttpClient();
                var response = await client.GetAsync(uri);
                result = await response.Content.ReadAsStringAsync();
            }
            catch (Exception e)
            {
                Console.Write(e.Message);
            }

            return result;
        }
```

## Expected Behavior
I expect to get back the values from the other controller. 

## Current Behavior
I get the following exception when attempting to resolve the DNS name:
This happens in the local cluster, and in our Azure cluster. 

I can resolve other hosts like https://jsonplaceholder.typicode.com/
```
{System.Net.Sockets.SocketException (11001): No such host is known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at AnotherApi.Controllers.ValuesController.Get() in C:\dev\expr\servicefabric\DebuggingDns\AnotherApi\Controllers\ValuesController.cs:line 21}
```

I have the manifest set as follows 
```
    <Service Name="AnotherApi" ServiceDnsName="anotherapi.debuggingdns" ServicePackageActivationMode="ExclusiveProcess">
      <StatelessService ServiceTypeName="AnotherApiType" InstanceCount="[AnotherApi_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
    <Service Name="AnApi" ServiceDnsName="anapi.debuggingdns" ServicePackageActivationMode="ExclusiveProcess">
      <StatelessService ServiceTypeName="AnApiType" InstanceCount="[AnApi_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
```
DnsService is running and the name shown below registers:
![image](https://user-images.githubusercontent.com/3843564/67430014-58d5cf80-f5af-11e9-8d3d-e985aca4c47c.png)

#### Service Fabric Runtime and SDK Version :
6.5.639.9590

#### Operating System :
Windows 10

#### Cluster Size :
Local cluster 1 node, cloud: 3 nodes

## Possible Workaround
I launch the services with -1 Instance count and hit localhost instead of DNS name. This is not a long term 

Appreciate any help on this.

**Comment by lzhgus** [comment]
any update on it?
