### ISSUE TITLE
"Service host failed to activate" When running Windows containers on local cluster

### ISSUE THREAD

**Issue by JRRJ** [microsoft/service-fabric#545]
On a local one-node cluster I am trying to run a Service Fabric application with four stateless services, all of them running containers whose images are using servercore:ltsc2019 as the parent image. When running the application, the containers do get created but they never start. After a few minutes the containers are removed and re-created, and this process keeps repeating without the containers ever starting. This is the error I'm observing in the explorer:
![image](https://user-images.githubusercontent.com/9662042/66792339-09a3e680-eead-11e9-83ab-2bec061ee735.png)

Resetting Docker to factory defaults fixes the issue, but if I create a new cluster, the problem returns. In either situation, I am able to run containers for these images directly using Docker or Docker Compose.

Here is a link to the [Service Fabric logs](https://drive.google.com/open?id=1B8T67vUvXsOpMydRsadeDncIUKMNHJsG) demonstrating this issue.

From the event logs: `Failed to start Container. ContainerName=sf-0-308f1943-2246-4c35-af1c-94c162a1de77_724ed3aa-9540-4e81-874e-8079e6c9dc70, ApplicationId=SearchType_App0, ApplicationName=fabric:/Search.System.Fabric.FabricException: Docker operation timed out. RequestUri=http://docker_engine/containers/sf-0-308f1943-2246-4c35-af1c-94c162a1de77_724ed3aa-9540-4e81-874e-8079e6c9dc70/start
   at Microsoft.ServiceFabric.ContainerServiceClient.ContainerServiceClient.<MakeRequestPrivateAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.ContainerServiceClient.ContainerServiceClient.<MakeRequestAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.ContainerServiceClient.ContainerOperation.<StartContainerAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hosting.ContainerActivatorService.Utility.<>c__DisplayClass14_0.<<ExecuteWithRetryOnTimeoutAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Hosting.ContainerActivatorService.Utility.<ExecuteWithRetryOnTimeoutAsync>d__15 1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hosting.ContainerActivatorService.ActivateContainerOperation.<StartContainerAsync>d__20.MoveNext()`

Additionally, looking at the Windows application logs for Docker events, this sequence of events is happening several times per minute:
`debug: Calling GET /v1.40/volumes/C`
`debug: Probing all drivers for volume with name: c`
`Post http://0.0.0.0:48081/Plugin.Activate: dial tcp 0.0.0.0:48081: connectex: No connection could be made because the target machine actively refused it.`
`Unable to connect to plugin: 0.0.0.0:48081/Plugin.Activate: Post http://0.0.0.0:48081/Plugin.Activate: dial tcp 0.0.0.0:48081: connectex: No connection could be made because the target ma...`

**Comment by afedyashov** [comment]
@JRRJ how do you get to those logs/event saying "Failed to start container"? Scanning SF Logs to find it, unsuccessfully. I have the same problem, wondering which diagnostic sources to look at.
