### ISSUE TITLE
Version changed error during deployment.

### ISSUE THREAD

**Issue by grassgit** [microsoft/service-fabric#561]
I am getting the following error on deployment: 
The content in ConfigPackage Name:Config and Version: in Service Manifest has changed, but the version number is the same.

The solution contains several services of which some have changed but mostly code only. I am using azure devops with ServiceFabricUpdateManifests@2 task to do the updates with option updateOnlyChanged enabled. This appears to be working correctly. Code and Config versions are updated when changed in all cases I have checked.
Deployment is done by a release pipeline with 
upgrade settings: Upgrade the Application enabled and the rest of the options at default. This fails with the error above.

I have check the config for the package in the message and compared the config files from the build outputs of the current version and the version number in the package and these files are identical (including line endings etc). 

The only changes to the configuration have been made through the application parameters files referenced by the publishing profile used by the deployment task. However as I understand the versioning this should not affect the apptype versioning.

Since we are in early development I can delete the entire app type and redeploy it but I need to get this working correctly. 
I found several similar issue but none of the solutions work in this case. Is this an issue with the deployment or am I missing something?

This is similar to 
* https://github.com/Azure/service-fabric-issues/issues/912 but there are no changes in the config so the update versions tasks works as expected. Using a diff package in this case would not work because the code of the package has changed.
* https://github.com/Azure/service-fabric-issues/issues/444 but I do not have compression enabled.

**Comment by HuaLi** [comment]
we hit the exactly same issue. 

btw:  /p:Deterministic=true is there, pdbs are deleted, and we are sure we only touch code part, no settings.xml change, no service manifest change

**Comment by mfmadsen** [comment]
Removing compression “solved” this issue for us. Obviously we would like to use compression to speed up uploads etc. but as soon as we turn on compression we see the exact same issue. Can you verify this experience?

**Comment by HuaLi** [comment]
no luck, we do not enable compression
![image](https://user-images.githubusercontent.com/459088/102439835-f7e24400-4059-11eb-8ec3-051361318096.png)

**Comment by mfmadsen** [comment]
We use these settings:
![image](https://user-images.githubusercontent.com/22656498/102450941-cf495280-4037-11eb-83fb-de000a2980f5.png)

**Comment by HuaLi** [comment]
Thanks Morten. I tried your suggestion and not works for us. :(
and I checked debug flag for our pipeline when running, and find below exception.  then I downloaded the drop and compare them using windiff, no difference.  I guess because of some other issue  the ImageBuilder crashed, but it report misleading message (XXX has changed but version is same).

/////////////////////    
System.Fabric.Management.ImageBuilder.FabricImageBuilderValidationException: The content in CodePackage Name:Code and Version:1.0.1.20201217.2 in Service Manifest 'EventActorPkg' has changed, but the version number is the same.
   at System.Fabric.Management.ImageBuilder.ImageBuilderUtility.TraceAndThrowValidationError(FabricErrorCode fabricErrorCode, String type, String format, Object[] args)
   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ParseCodePackageAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<CreateServiceManifestAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ParseServiceManifestAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ParseApplicationPackageAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Fabric.Management.ImageBuilder.ApplicationProvisionOperation.<ProvisionApplicationAsync>d__20.MoveNext()
