### ISSUE TITLE
I want to update the service fabric cluster config settings, but when I test the config ,it runs error.

### ISSUE THREAD

**Issue by sall84993356** [microsoft/service-fabric#576]
Stand alone cluster ,three nodes vm . I used gmsa to access the sql server by domain account.

I used this commond :
.\TestConfiguration.ps1 -ClusterConfigFilePath .\ClusterConfig.Unsecure.MultiMachinenew.json -OldClusterConfigFilePath .\ClusterConfig.Unsecure.MultiMachine.json

Trace folder already exists. Traces will be written to existing trace folder: D:\Microsoft.Azure.ServiceFabric.WindowsServer-new\DeploymentTraces
Running Best Practices Analyzer...
Test Config failed with exception: System.AggregateException: One or more errors occurred. ---> System.TypeInitializationException: The type initializer for 'System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility' threw an exception. ---> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Net.IPHostEntry> System.Fabric.Common.Helpers.GetHostEntryFromName(System.String)'.
   at System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility.GetCurrentMachineNames()
   at System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility..cctor()
   --- End of inner exception stack trace ---
   at System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility.IsValidIPAddressOrFQDN(String ipAddressOrFQDN)
   at Microsoft.ServiceFabric.DeploymentManager.Model.NodeDescriptionGA.Verify()
   at Microsoft.ServiceFabric.DeploymentManager.Model.StandAloneInstallerJsonModelBase.ValidateNodeList()
   at Microsoft.ServiceFabric.DeploymentManager.Model.StandAloneInstallerJSONModelOctober2017.ValidateModel()
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.IsJsonConfigModelValid(StandAloneInstallerJsonModelBase config, StandAloneInstallerJsonModelBase oldConfig, Boolean validateDownNodes, Boolean throwIfError)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.AnalyzeClusterSetup(String configPath, String oldConfigPath, String cabPath, Boolean usingClusterManifest, FabricPackageType fabricPackageType, Boolean isForcedRun, Int32 maxPercentFailedNodes)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.<>c__DisplayClass1_0.<AnalyzeClusterSetupAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.BpaAnalyzeClusterSetup(String clusterConfigPath, String oldClusterConfigPath, String fabricPackagePath, Int32 maxPercentFailedNodes)
   at Microsoft.ServiceFabric.Powershell.ClusterCmdletBase.TestConfig(String clusterConfigPath, String oldClusterConfigPath, String fabricPackagePath, Int32 maxPercentFailedNodes)
   at Microsoft.ServiceFabric.Powershell.TestConfig.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
---> (Inner Exception #0) System.TypeInitializationException: The type initializer for 'System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility' threw an exception. ---> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Net.IPHostEntry> System.Fabric.Common.Helpers.GetHostEntryFromName(System.String)'.
   at System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility.GetCurrentMachineNames()
   at System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility..cctor()
   --- End of inner exception stack trace ---
   at System.Fabric.Management.WindowsFabricValidator.FabricValidatorUtility.IsValidIPAddressOrFQDN(String ipAddressOrFQDN)
   at Microsoft.ServiceFabric.DeploymentManager.Model.NodeDescriptionGA.Verify()
   at Microsoft.ServiceFabric.DeploymentManager.Model.StandAloneInstallerJsonModelBase.ValidateNodeList()
   at Microsoft.ServiceFabric.DeploymentManager.Model.StandAloneInstallerJSONModelOctober2017.ValidateModel()
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.IsJsonConfigModelValid(StandAloneInstallerJsonModelBase config, StandAloneInstallerJsonModelBase oldConfig, Boolean validateDownNodes, Boolean throwIfError)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.AnalyzeClusterSetup(String configPath, String oldConfigPath, String cabPath, Boolean usingClusterManifest, FabricPackageType fabricPackageType, Boolean isForcedRun, Int32 maxPercentFailedNodes)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.<>c__DisplayClass1_0.<AnalyzeClusterSetupAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

When I tested this commond : 
.\TestConfiguration.ps1 -ClusterConfigFilePath .\ClusterConfig.Unsecure.MultiMachine.json
It showed the same error

**Comment by maburlik** [comment]
This issue is the result of a conflict between the dll versions found in the standalone package used to run CreateCluster/AddNode and the version of dlls picked up from another location i.e. GAC of the current machine. If SF is installed on the current node with a version differing from the release version of the standalone package, there is a risk of hitting this issue. For this reason it is advised to either keep these component versions in sync or to execute standalone cluster operations from the standalone package from a distinct controller machine where either
1. Installed SF runtime version is in sync with the standalone package or
2. SF is not installed - where there are no alternate bits to be found elsewhere on the machine

In the future if you hit similar issues you can identify the sources of loaded dlls using Fusion Logs:
https://techcommunity.microsoft.com/t5/iis-support-blog/fusion-log-viewer-fuslogvw-exe/ba-p/784396
https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer
