### ISSUE TITLE
Copy-ServiceFabricApplicationPackage fails regularily when trying to run SF application on local cluster

### ISSUE THREAD

**Issue by Sossenbinder** [microsoft/service-fabric#583]
I am developing a Service Fabric application locally, and I, seemingly randomly, tend to see the following error message when trying to start from VS2017:
```
    4>Copying application to image store...
    4>Copy-ServiceFabricApplicationPackage : Failed to copy 1 items while copying from source 
    4>E:\Programmieren\ASP.NET_Core\MooMed\MooMed\MooMed.Fabric\pkg\Debug to destination 
    4>C:\SfDevCluster\Data\ImageStoreShare\MooMed.FabricType
    4>At C:\Program Files\Microsoft SDKs\Service 
    4>Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:274 char:9
    4>+         Copy-ServiceFabricApplicationPackage -ApplicationPackagePath  ...
    4>+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    4>    + CategoryInfo          : InvalidData: (:) [Copy-ServiceFabricApplicationPackage], InvalidDataException
    4>    + FullyQualifiedErrorId : CopyApplicationPackageErrorId,Microsoft.ServiceFabric.Powershell.CopyApplicationPackage
```

Apparently something goes wrong here, but I don't really know what the problem is.

Running `Get-ServiceFabricApplicationType` through powershell shows me the following errorcode: `FABRIC_E_IMAGEBUILDER_UNEXPECTED_ERROR`. However, I can barely find any kind of documentation.

I can't really say what might be the cause of this as well, as it tends to appear here and there, but it often goes away after rebooting my computer / resetting the local cluster.

Is there any information you can provide me? Documentation is really scarce regarding what happens in the Publish-NewServiceFabricApplication.ps1

Edit: I was able to run it with -Verbose flags, this is what I got now:

```
    4>Copying application to image store...
    4>VERBOSE: System.IO.InvalidDataException: Failed to copy 1 items while copying from source 
    4>E:\Programmieren\ASP.NET_Core\MooMed\MooMed\MooMed.Fabric\pkg\Debug to destination 
    4>C:\SfDevCluster\Data\ImageStoreShare\MooMed.FabricType
    4>
    4>   at System.Fabric.ImageStore.FolderCopy.Copy(String source, String destination)
    4>
    4>   at System.Fabric.ImageStore.FileImageStore.CopyCallerHoldsReaderLock(String source, String destination, CopyFlag 
    4>copyFlag, TimeoutHelper helper)
    4>
    4>   at System.Fabric.ImageStore.FileImageStore.UploadContent(String storeDestination, String localSource, 
    4>IImageStoreProgressHandler handler, TimeSpan timeout, CopyFlag copyFlag, Boolean acquireSourceReaderLock)
    4>
    4>   at Microsoft.ServiceFabric.Powershell.CommonCmdletBase.UploadToImageStore(String imageStoreConnectionString, String 
    4>src, String des, UploadProgressHandler progressHandler)
    4>
    4>   at Microsoft.ServiceFabric.Powershell.CopyApplicationPackage.ProcessRecord()
    4>Copy-ServiceFabricApplicationPackage : Failed to copy 1 items while copying from source 
    4>E:\Programmieren\ASP.NET_Core\MooMed\MooMed\MooMed.Fabric\pkg\Debug to destination 
    4>C:\SfDevCluster\Data\ImageStoreShare\MooMed.FabricType
    4>At C:\Program Files\Microsoft SDKs\Service 
    4>Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:274 char:9
    4>+         Copy-ServiceFabricApplicationPackage -ApplicationPackagePath  ...
    4>+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    4>    + CategoryInfo          : InvalidData: (:) [Copy-ServiceFabricApplicationPackage], InvalidDataException
    4>    + FullyQualifiedErrorId : CopyApplicationPackageErrorId,Microsoft.ServiceFabric.Powershell.CopyApplicationPackage
    4> 
    4>Finished executing script 'Deploy-FabricApplication.ps1'.
```
During the script run I notices that the application is indeed copied from from my pkg/Debug to the ImageStoreShare, but then disappears again. I'm not sure if this is due to the error and clean up in the background or whether something else could have deleted this.

**Comment by sunilbindra** [comment]
we are facing the same issue on on prem cluster. I am using Octopus deploy, and running powershell script to copy the package. Script is running on Target Machine. Package is valid and I am able to connect on the cluster, just while copying it fails. The script works fine if RDP on machine and run the script. Any Idea why this is happening, We are using GMSA (Windows Security).

Copy-ServiceFabricApplicationPackage `
        -ApplicationPackagePath $packageSourcePath `
        -ApplicationPackagePathInImageStore $ImageStoreName_$appVersion `
        -ImageStoreConnectionString $ImageConnectionString.Value `
        -TimeoutSec 2700 -Verbose

**Comment by amitaysh** [comment]
Hi,
Had the same issue in our team, eventually found a weird solution that worked for us all... just run the "Publish-NewServiceFabricApplication.ps1" PowerShell command manually as admin, and only then run it via VisualStudio. (this script already includes the Copy-ServiceFabricApplicationPackage command)
You can take it from your VisualStudio ServiceFabric output pane, just take the actual command from inside the double quotes (don't forget the dot!)
The full command should look like this:
`powershell -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -Command ". C:\.................. "`
So you should run only the `. C:\....... ` part (**with** the prefix dot)

Hope it will help you as well :)

**Comment by amitaysh** [comment]
found a better solution for this...
seems like sometimes the boolean values sent by VS converted to string.
this solves the issue in 100% of the times we tried:
in file `C:\Program Files\Microsoft SDKs\Service Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1`
line 274 - Change $CompressPackage with $false
