### ISSUE TITLE
COMException: Exception from HRESULT: 0x80071BFD

### ISSUE THREAD

**Issue by PeterJD** [microsoft/service-fabric#591]
Downloaded below app from Github after many hours of study the app, when implementing came across  the below error
Is there an issue Service Fabric or a just the code I implemented the code localy using envirement variable set to --> Local.xml

Any help would be appreciate
Kind regards

https://github.com/dzimchuk/book-fast-service-fabric

-----------------------------------------------------------------------------------------------------
System.InvalidOperationException
  HResult=0x80131509
  Message=The operation is invalid.
  Source=System.Fabric
  StackTrace:
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
   at System.Fabric.Interop.Utility.RunInMTA[TResult](Func`1 func)
   at Microsoft.Diagnostics.EventFlow.ServiceFabric.ServiceFabricHealthReporter..ctor(String entityIdentifier)
   at Microsoft.Diagnostics.EventFlow.ServiceFabric.ServiceFabricDiagnosticPipelineFactory.CreatePipeline(String healthEntityName, String configurationFileName, String configurationPackageName)
   at BookFast.Files.Program.Main() in C:\book-fast-service-fabric-CMS\BookFast.Files\Program.cs:line 17

Inner Exception 1:COMException: Exception from HRESULT: 0x80071BFD
--------------------------------------------------------------------------------------------------------------------------------

using Microsoft.Diagnostics.EventFlow.ServiceFabric;
using Microsoft.ServiceFabric.Services.Runtime;
using System;
using System.Diagnostics;
using System.Threading;

namespace BookFast.Files
{
    internal static class Program
    {
        private static void Main()
        {
            try
            {
                using (var terminationEvent = new ManualResetEvent(initialState: false))
                { //Line 17
                    using (var diagnosticsPipeline = ServiceFabricDiagnosticPipelineFactory.CreatePipeline("BookFast-Files-DiagnosticsPipeline"))
                    {
                        Console.CancelKeyPress += (sender, eventArgs) => Shutdown(diagnosticsPipeline, terminationEvent);

                        AppDomain.CurrentDomain.UnhandledException += (sender, unhandledExceptionArgs) =>
                        {
                            ServiceEventSource.Current.UnhandledException(unhandledExceptionArgs.ExceptionObject?.ToString() ?? "(no exception information)");
                            Shutdown(diagnosticsPipeline, terminationEvent);
                        };

                        ServiceRuntime.RegisterServiceAsync("FilesServiceType",
                                    context => new FilesService(context)).GetAwaiter().GetResult();

                        ServiceEventSource.Current.ServiceTypeRegistered(Process.GetCurrentProcess().Id, typeof(FilesService).Name);

                        terminationEvent.WaitOne();
                    } 
                }
            }
            catch (Exception e)
            {
                ServiceEventSource.Current.ServiceHostInitializationFailed(e.ToString());
                throw;
            }
        }

        private static void Shutdown(IDisposable disposable, ManualResetEvent terminationEvent)
        {
            try
            {
                disposable.Dispose();
            }
            finally
            {
                terminationEvent.Set();
            }
        }
    }
}

**Comment by PTC-JoshuaMatthews** [comment]
I got this same error when I accidentally left my fabric service as a visual studio startup project, I assume this was where it chokes due to not being hosted in service fabric.
