### ISSUE TITLE
Copy-ServiceFabricApplicationPackage to image store never finishes

### ISSUE THREAD

**Issue by jdvor** [microsoft/service-fabric#602]
I'm unable to deploy Service Fabric application to Azure Service Fabric cluster; specifically to  copy the deployment package to image store using Powershell scripts from Service Fabric SDK.

_Azure Service Fabric cluster:_
New single node cluster (VM is Ubuntu 16.04)
Service Fabric version: **6.4.639.1**
Nothing has yet been deployed on it. 
Both Azure blade and Service Fabric Explorer shows node as green / ready and no ongoing upgrades.

_Client machine:_
Microsoft Azure Service Fabric SDK **3.3.654** 
Using Powershell to deploy the app:
`C:\Program Files\Microsoft SDKs\Service Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1`

`Copy-ServiceFabricApplicationPackage` (L:247) hangs and never proceeds any further beyond several K transfered. 
I've added `-ShowProgress` `-ShowProgressIntervalMilliseconds 3000` to see more details.
It shows that it transfered some bytes and than stops (usually 2-4K).

So far I've tried (on client machine):
* Turning off firewall completely.
* Removing local development cluster and stopping FabricHostSvc, because of the suggestions in microsoft/service-fabric-issues#813 

I don't know how to SSH into the VM yet, but once I'll found out I will add any relevant details.
I've also quickly browsed through cluster logs which are shoveled to Azure Table Storage, but so far did not find anything interesting or pertaining to image store.

**Comment by rojo69** [comment]
I frequently use four different Wi-Fi networks. On two of them (both Apple's AirPort) the transfer always fail after about 35 files successfully uploaded. The other two works fine. Also internet sharing from my cell phone succeeds.

**Comment by jaydavid** [comment]
I don't know if this will be helpful to anyone, but I was facing this issue for a while and eventually figured out what was causing it - at least I believe I did.

I had Docker for Windows and Kubernetes set up locally through Hyper-V as well as a minikube vm for some other projects.  My network traffic, as a consequence, was always routed through a network bridge and a vEthernet connection (minikube).

I'm not a network engineer or anything, so I was kind of just poking around there, but I ended up removing the minikube vm, disabling the vEthernet adapters, and un-bridging my wifi connection and it immediately worked.

Hopefully this helps at least one person facing this issue.

**Comment by Adebeer** [comment]
This issue is a real pain as we frequently have to retry registering packages multiple times.

Part of the issue is that we're a global company spanning multiple regions around the globe. In our case we have 3 global regions and all devs using same Azure DevOps namespace hosted in North America. Problem is that, because we're using hosted Azure agents - these are all hosted in North America (there's no customization around this as far as I'm aware) - so for our clusters hosted in other regions, Copy Package frequently times out.

Our option thus seems to not use azure hosted agents and instead opt for a local agent (although from other users experience, doesn't seem a fool proof solution) and/or perhaps using a workaround to copy packages to a local location first and then deploy from there. All in all, bit of a sub-optimal experience - most of our packages are only ~300MB so they're not even that large. We've set our register/copy azure dev-ops task to timeout after 15 minutes as, when it works it typically takes < 5 minutes - increasing timeout/waiting longer doesn't seem to achieve anything other than blocking build agents for other builds.

**2021-07-26T03:15:23.7787726Z Using ImageStoreConnectionString='fabric:ImageStore'
2021-07-26T03:26:41.4738544Z ##[debug]Re-evaluate condition on job cancellation for step: 'Register Package in SF Image Store'.
2021-07-26T03:26:51.6488922Z ##[error]The operation was canceled.**
2021-07-26T03:26:51.6496177Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)

**Comment by jdvor** [comment]
Apparently nothing will be done.
