### ISSUE TITLE
Service Fabric installation getting timed out

### ISSUE THREAD

**Issue by raviteja-kurra** [microsoft/service-fabric#698]
Hi, 
I am getting the below error while installing the Service fabric. 

PS D:\MTS\Utils\SF\SFInstaller> .\TestConfiguration.ps1 -ClusterConfigFilePath .\ClusterConfig.Unsecure.DevCluster.json
-FabricRuntimePackagePath ..\MicrosoftAzureServiceFabric.6.0.219.9494.cab
Trace folder already exists. Traces will be written to existing trace folder: D:\MTS\Utils\SF\SFInstaller\DeploymentTrac
es
Running Best Practices Analyzer...
Best Practices Analyzer completed successfully.

LocalAdminPrivilege        : True
IsJsonValid                : True
IsCabValid                 : True
RequiredPortsOpen          : True
RemoteRegistryAvailable    : True
FirewallAvailable          : True
RpcCheckPassed             : True
NoConflictingInstallations : True
FabricInstallable          : True
DataDrivesAvailable        : True
Passed                     : True

PS D:\MTS\Utils\SF\SFInstaller> .\CreateServiceFabricCluster.ps1 -ClusterConfigFilePath .\ClusterConfig.Unsecure.DevClus
ter.json -AcceptEULA -Force -FabricRuntimePackagePath ..\MicrosoftAzureServiceFabric.6.0.219.9494.cab
Creating Service Fabric Cluster...
If it's taking too long, please check in Task Manager details and see if Fabric.exe for each node is running. If not, pl
ease look at: 1. traces in DeploymentTraces directory and 2. traces in FabricLogRoot configured in ClusterConfig.json.
Trace folder already exists. Traces will be written to existing trace folder: D:\MTS\Utils\SF\SFInstaller\DeploymentTrac
es
Running Best Practices Analyzer...
Best Practices Analyzer completed successfully.
Creating Service Fabric Cluster...
Processing and validating cluster config.
Configuring nodes.
Default installation directory chosen based on system drive of machine 'localhost'.
Copying installer to all machines.
Configuring machine 'localhost'.
Machine localhost configured.
Running Fabric service installation.
Successfully started FabricInstallerSvc on machine localhost
Timed out waiting for Installer Service to complete for machine localhost. Investigation order: FabricInstallerService -
> FabricSetup -> FabricDeployer -> Fabric
CreateCluster Error: System.AggregateException: One or more errors occurred. ---> System.ServiceProcess.TimeoutException
: Timed out waiting for Installer Service to complete for machine localhost. Investigation order: FabricInstallerService
 -> FabricSetup -> FabricDeployer -> Fabric
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(Str
ing machineName, ServiceController installerSvc)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallel
Options, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOption
s, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithE
verything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.RunFabricServices(List`1 machines, FabricPacka
geType fabricPackageType)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
---> (Inner Exception #0) System.ServiceProcess.TimeoutException: Timed out waiting for Installer Service to complete fo
r machine localhost. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(Str
ing machineName, ServiceController installerSvc)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

Trace folder already exists. Traces will be written to existing trace folder: D:\MTS\Utils\SF\SFInstaller\DeploymentTrac
es
Cleaning up faulted installation.
Removing configuration from machine localhost
FabricInstallerSvc timeout on machine localhost. Cleaning up to avoid environment corruption.
Unable to stop FabricInstallerSvc service because System.InvalidOperationException: Cannot stop FabricInstallerSvc servi
ce on computer 'localhost'. ---> System.ComponentModel.Win32Exception: The service cannot accept control messages at thi
s time
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Stop()
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.Stop(String serviceName, String machineName)
System.ServiceProcess.TimeoutException: Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceInStoppedState(String machineName, String s
erviceName)
   at System.Fabric.FabricDeployer.RemoveNodeConfigOperation.RemoveNodeConfigurationXCopy(String machineName, Boolean de
leteLog, String nodeName, Boolean removeNodeState)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disable
FileTrace)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfigurationInner(Boolean deleteLog, FabricPackageTy
pe fabricPackageType, String machineName)
System.ServiceProcess.TimeoutException: Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceInStoppedState(String machineName, String s
erviceName)
   at System.Fabric.FabricDeployer.RemoveNodeConfigOperation.RemoveNodeConfigurationXCopy(String machineName, Boolean de
leteLog, String nodeName, Boolean removeNodeState)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disable
FileTrace)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfigurationInner(Boolean deleteLog, FabricPackageTy
pe fabricPackageType, String machineName)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfiguration(Boolean deleteLog, FabricPackageType fa
bricPackageType, String machineName)
RemoveNodeConfiguration did not complete successfully on machine localhost. Error: System.ServiceProcess.TimeoutExceptio
n: Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceInStoppedState(String machineName, String s
erviceName)
   at System.Fabric.FabricDeployer.RemoveNodeConfigOperation.RemoveNodeConfigurationXCopy(String machineName, Boolean de
leteLog, String nodeName, Boolean removeNodeState)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disable
FileTrace)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfigurationInner(Boolean deleteLog, FabricPackageTy
pe fabricPackageType, String machineName)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfiguration(Boolean deleteLog, FabricPackageType fa
bricPackageType, String machineName)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass15_0.<RemoveNodeConfiguration
Async>b__1(String machineName)
Rollback failed with System.AggregateException: One or more errors occurred. ---> System.ServiceProcess.TimeoutException
: Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceInStoppedState(String machineName, String s
erviceName)
   at System.Fabric.FabricDeployer.RemoveNodeConfigOperation.RemoveNodeConfigurationXCopy(String machineName, Boolean de
leteLog, String nodeName, Boolean removeNodeState)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disable
FileTrace)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfigurationInner(Boolean deleteLog, FabricPackageTy
pe fabricPackageType, String machineName)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfiguration(Boolean deleteLog, FabricPackageType fa
bricPackageType, String machineName)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass15_0.<RemoveNodeConfiguration
Async>b__1(String machineName)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallel
Options, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOption
s, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithE
verything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass15_0.<RemoveNodeConfiguration
Async>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<BestEffortRollback>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
---> (Inner Exception #0) System.ServiceProcess.TimeoutException: Time out has expired and the operation has not been co
mpleted.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceInStoppedState(String machineName, String s
erviceName)
   at System.Fabric.FabricDeployer.RemoveNodeConfigOperation.RemoveNodeConfigurationXCopy(String machineName, Boolean de
leteLog, String nodeName, Boolean removeNodeState)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disable
FileTrace)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfigurationInner(Boolean deleteLog, FabricPackageTy
pe fabricPackageType, String machineName)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfiguration(Boolean deleteLog, FabricPackageType fa
bricPackageType, String machineName)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass15_0.<RemoveNodeConfiguration
Async>b__1(String machineName)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

Create Cluster failed. For more information please look at traces in FabricLogRoot.
Create Cluster failed with exception: System.AggregateException: One or more errors occurred. ---> System.AggregateExcep
tion: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ServiceProce
ss.TimeoutException: Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceInStoppedState(String machineName, String s
erviceName)
   at System.Fabric.FabricDeployer.RemoveNodeConfigOperation.RemoveNodeConfigurationXCopy(String machineName, Boolean de
leteLog, String nodeName, Boolean removeNodeState)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disable
FileTrace)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfigurationInner(Boolean deleteLog, FabricPackageTy
pe fabricPackageType, String machineName)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfiguration(Boolean deleteLog, FabricPackageType fa
bricPackageType, String machineName)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass15_0.<RemoveNodeConfiguration
Async>b__1(String machineName)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallel
Options, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOption
s, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithE
verything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass15_0.<RemoveNodeConfiguration
Async>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<BestEffortRollback>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManager.<CreateClusterAsync>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Powershell.ClusterCmdletBase.NewCluster(String clusterConfigurationFilePath, String fabric
PackageSourcePath, Boolean noCleanupOnFailure, Boolean force)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or
 more errors occurred. ---> System.ServiceProcess.TimeoutException: Time out has expired and the operation has not been
completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceInStoppedState(String machineName, String s
erviceName)
   at System.Fabric.FabricDeployer.RemoveNodeConfigOperation.RemoveNodeConfigurationXCopy(String machineName, Boolean de
leteLog, String nodeName, Boolean removeNodeState)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disable
FileTrace)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfigurationInner(Boolean deleteLog, FabricPackageTy
pe fabricPackageType, String machineName)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfiguration(Boolean deleteLog, FabricPackageType fa
bricPackageType, String machineName)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass15_0.<RemoveNodeConfiguration
Async>b__1(String machineName)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallel
Options, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOption
s, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithE
verything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass15_0.<RemoveNodeConfiguration
Async>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<BestEffortRollback>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManager.<CreateClusterAsync>d__2.MoveNext()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ServiceProcess.TimeoutExce
ption: Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceInStoppedState(String machineName, String s
erviceName)
   at System.Fabric.FabricDeployer.RemoveNodeConfigOperation.RemoveNodeConfigurationXCopy(String machineName, Boolean de
leteLog, String nodeName, Boolean removeNodeState)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disable
FileTrace)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfigurationInner(Boolean deleteLog, FabricPackageTy
pe fabricPackageType, String machineName)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfiguration(Boolean deleteLog, FabricPackageType fa
bricPackageType, String machineName)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass15_0.<RemoveNodeConfiguration
Async>b__1(String machineName)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallel
Options, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOption
s, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithE
verything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass15_0.<RemoveNodeConfiguration
Async>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<BestEffortRollback>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
---> (Inner Exception #0) System.ServiceProcess.TimeoutException: Time out has expired and the operation has not been co
mpleted.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.GetServiceInStoppedState(String machineName, String s
erviceName)
   at System.Fabric.FabricDeployer.RemoveNodeConfigOperation.RemoveNodeConfigurationXCopy(String machineName, Boolean de
leteLog, String nodeName, Boolean removeNodeState)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disable
FileTrace)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfigurationInner(Boolean deleteLog, FabricPackageTy
pe fabricPackageType, String machineName)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.RemoveNodeConfiguration(Boolean deleteLog, FabricPackageType fa
bricPackageType, String machineName)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass15_0.<RemoveNodeConfiguration
Async>b__1(String machineName)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
<---
<---

**Comment by maburlik** [comment]
To troubleshoot, you can preserve fabric logs and find them in the event viewer if you run with flag -NoCleanupOnFailure. Also as of a 7.0 CU the timeout parameters have been piped through the CreateCluster & AddNode APIs.

.\CreateServiceFabricCluster.ps1 -ClusterConfigFilePath .\config.json -AcceptEULA -Force -NoCleanupOnFailure -FabricRuntimePackagePath ..\MicrosoftServiceFabric.cab -TimeoutInSeconds 500
