### ISSUE TITLE
service fabric local cluster manager failed to set up local cluster

### ISSUE THREAD

**Issue by sanjnaputhran-gep** [microsoft/service-fabric#716]
I am trying to setup the service fabric on local env for the first time. The installation was successful.
However, when trying to setup local cluster - Node1, I get an error "service fabric local cluster manager failed to set up local cluster". I did not make any changes config files and trying to install as is. 
I also tried to re-set the "Reset Local Cluster". I still get the same error as "service fabric local cluster manager failed to reset".

I am using windows 10 ;  Visual studio 2017; Service Fabric SDK version 3.2.176

Additional information from the Event log - 
Task Category - FabricDeployer:
 System.IO.IOException: The network path was not found.
   at Microsoft.Win32.RegistryKey.Win32ErrorStatic(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.OpenRemoteBaseKey(RegistryHive hKey, String machineName, RegistryView view)
   at System.Fabric.FabricDeployer.Utility.GetTempPathInner(String machineName)
   at System.Fabric.FabricDeployer.Utility.GetTempPath(String machineName)

Task Category - FabricDeployer:
System.IO.IOException: The network path was not found.

   at Microsoft.Win32.RegistryKey.Win32ErrorStatic(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.OpenRemoteBaseKey(RegistryHive hKey, String machineName, RegistryView view)
   at System.Fabric.FabricDeployer.Utility.GetTempPathInner(String machineName)
   at System.Fabric.FabricDeployer.Utility.GetTempPath(String machineName)
   at System.Fabric.FabricDeployer.RemoveOperation.CollectEventLogs()
   at System.Fabric.FabricDeployer.RemoveOperation.CleanupDeployment(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperationPrivate(DeploymentParameters parameters)
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disableFileTrace)
   at System.Fabric.FabricDeployer.Program.Main(String[] args)

What could be the issue? How do I debug?﻿ Can you help?
Thank you

**Comment by maburlik** [comment]
The cluster setup issue appears to have been resolved and the reset cluster FabricDeployer Remove operation error "System.IO.IOException: The network path was not found." has been fixed in a 7.0 CU.
