### ISSUE TITLE
Copy-ServiceFabricApplicationPackage doesn't support long paths

### ISSUE THREAD

**Issue by OlegKarasik** [microsoft/service-fabric#801]
If you would try to run ```Copy-ServiceFabricApplicationPackage``` for the package directory that exceeded windows MAX_PATH then it would result in error:

```
VERBOSE: System.Fabric.FabricException: An error occurred during this operation.  Please check the trace logs for more
details. ---> System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM
component.
   at System.Fabric.Interop.NativeImageStore.ArchiveApplicationPackage(IntPtr appPackageRootDirectory,
IFabricNativeImageStoreProgressEventHandler progressEventHandler)
   at System.Fabric.Management.ImageStore.ImageStoreUtility.ArchiveApplicationPackageHelper(String
appPackageRootDirectory, IImageStoreProgressHandler progressHandler)
   at System.Fabric.Interop.Utility.<>c__DisplayClass27_0.<WrapNativeSyncInvoke>b__0()
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String
functionArgs)
   --- End of inner exception stack trace ---
   at System.Fabric.Interop.Utility.RunInMTA(Action action)
   at Microsoft.ServiceFabric.Powershell.CopyApplicationPackage.CompressOrUncompressIfNeeded(String sourcePath,
UploadProgressHandler progressHandler)
   at Microsoft.ServiceFabric.Powershell.CopyApplicationPackage.ProcessRecord()
```

Inside the trace logs there would be a message:
TryZipDirectory failed: 
```
src=<source folder> dest=<destination folder>\Code.zip error=System.IO.DirectoryNotFoundException: Could not find a part of the path '<name of the file will very long path>'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.DoCreateEntryFromFile(ZipArchive destination, String sourceFileName, String entryName, Nullable`1 compressionLevel)
   at System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
   at TryZipDirectory(Char* srcDirectoryPath, Char* destFileName, Char* errorMessageBuffer, Int32 errorMessageBufferSize)
```

Important to mention that this happens only when -CompressPackage switch is specified.

**Comment by craftyhouse** [comment]
I believe this is clearer now, but is still limited by .Net framework’s maximum path limit

Recent trace example:
Note that long paths exceeding the Windows MAX_PATH limit are not supported for compressed packages.  System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
