### ISSUE TITLE
Copy-ServiceFabricApplicationPackage requires re-authorization

### ISSUE THREAD

**Issue by NickDarvey** [microsoft/service-fabric#894]
**Repro**
```
Connect-ServiceFabricCluster -ConnectionEndpoint cluster:19000 -AzureActiveDirectory

# Interactive prompt for authorization occurs

Copy-ServiceFabricApplicationPackage -ApplicationPackagePath C:\applicationpackage -ImageStoreConnectionString fabric:ImageStore -ApplicationPackagePathInImageStore ReactorType 
```

**Expected**
Application package is copied to image store.

**Actual**
Interactive prompt for authorization occurs, again. 
If it's authorized, it continues to copy the application package. f it's not authorized (user cancels), or if the PowerShell script is running headless, or if inside the Visual Studio PowerShell Interactive Window; it fails with:
```
[ERROR] Copy-ServiceFabricApplicationPackage : Exception has been thrown by the target of an invocation.
```

and with `-Verbose`:
```
[VERBOSE] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at System.Fabric.Interop.Utility.RunInMTA(Action action)
   at System.Fabric.Management.ImageStore.NativeImageStoreClient.UploadContent(String remoteDestination, String localSource, IImageStoreProgressHandler progressHandler, TimeSpan timeout, CopyFlag imageCopyFlag, Boolean acquireSourceReaderLock)
   at System.Fabric.Management.ImageStore.NativeImageStoreClient.UploadContent(String remoteDestination, String localSource, TimeSpan timeout, CopyFlag imageCopyFlag, Boolean acquireSourceReaderLock)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Fabric.ImageStoreProxy.UploadContent(String sourceFullPath, String destinationRelativePathInImageStore, TimeSpan timeout)
   at System.Fabric.FabricClient.ImageStoreClient.Upload(String sourceFullPath, String destinationRelativePath, Boolean shouldOverwrite, TimeSpan timeout, IImageStoreProgressHandler progressHandler)
   at Microsoft.ServiceFabric.Powershell.CommonCmdletBase.UploadToImageStore(String imageStoreConnectionString, String src, String des, UploadProgressHandler progressHandler)
   at Microsoft.ServiceFabric.Powershell.CopyApplicationPackage.ProcessRecord()
```

**Comment by sunilbindra** [comment]
I am using on Prem-Cluster and using powershell script to copy the package. I am using octopus for deployment and running PS script on target machine which contains teh code to copy the package. Script works fine when I RDP on machine. But getting unauthorised error while running the same script from Octopus.

Any Idea.

Import-Module ServiceFabric
Write-Output "Start Connecting to the Cluster"
Connect-ServiceFabricCluster 
Write-Output "Successfully Connected to Cluster"

Copy-ServiceFabricApplicationPackage `
        -ApplicationPackagePath $PackageLocation$PackageName `
        -ApplicationPackagePathInImageStore $ImageStoreName_$appVersion `
        -ImageStoreConnectionString $ImageConnectionString.Value `
        -TimeoutSec 2700 -Verbose
