### ISSUE TITLE
StandAloneCluster.cs fail to read WRPSettings.xml when <Section Name="WrpSettings"> and Parameters provided.

### ISSUE THREAD

**Issue by schuelter** [microsoft/service-fabric#945]
From:
https://github.com/microsoft/service-fabric/blob/master/src/prod/src/managed/Api/Dlls/Microsoft.ServiceFabric.DeploymentManager/Common/StandAloneCluster.cs
Lines
```
315: var parameter = section.Parameter.FirstOrDefault(item => item.Name == parameterName);
316: return parameter == null ? defaultValue : parameter.Name;
```

Line 316 it should return **parameter.Value** instead of.

StandAloneCluster.cs fail to read WRPSettings.xml when Section Name="WrpSettings" and Parameters provided. 

```
  <Section Name="WrpSettings">
	<Parameter Name="ServiceConnectionEndpointPort" Value="9027"/>
  </Section>
```

Below the error message:

_Test Config failed with exception: System.AggregateException: One or more errors occurred. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Microsoft.ServiceFabric.DeploymentManager.Common.StandAloneCluster.GenerateSettings(SettingsType wrpSettings, IClusterTopology topology)
   at Microsoft.ServiceFabric.DeploymentManager.Common.StandaloneSettingsValidator..ctor(StandAloneInstallerJsonModelBase inputConfiguration)
   at Microsoft.ServiceFabric.DeploymentManager.BPA.BestPracticesAnalyzer.IsJsonConfigModelValid(StandAloneInstallerJsonModelBase config, StandAloneInstallerJsonModelBase oldConfig, Boolean validateDownNodes, Bo
olean throwIfError)_

**Comment by dtrailin** [comment]
This should be resolved in the next major release of service fabric.
