### ISSUE TITLE
Using EncryptionUtility to Encrypt/Decrypt Text

### ISSUE THREAD

**Issue by temelj** [microsoft/service-fabric#949]
I am trying to encrypt/decrypt text given a cert thumbprint in the my service fabric app startup.

```
var encrypt = EncryptionUtility.EncryptText("testing123", "eb f6 36 ba 23 10 d3 3c 82 69 a1 7c 08 60 ad c0 fb 2e 60 bf", "My");

var decrypted = EncryptionUtility.DecryptText(encrypt, StoreLocation.LocalMachine);
```

I have an equivalent PowerShell script that actually works
```
# Encrypt Text
$thumbprint='eb f6 36 ba 23 10 d3 3c 82 69 a1 7c 08 60 ad c0 fb 2e 60 bf'
$encryptedText = Invoke-ServiceFabricEncryptText -Text 'test123' -CertThumbprint $thumbprint -CertStore -StoreLocation LocalMachine -StoreName My

# Decrypt Text
Invoke-ServiceFabricDecryptText -CipherText $encryptedText -StoreLocation "LocalMachine"
```

## Current Behavior
DecryptText fails with:
Cannot find the certificate and private key to use for decryption. (Exception from HRESULT: 0x8009200C)

Stack Trace:
```
   at System.Fabric.Security.EncryptionUtility.DecryptText(String textToDecrypt, StoreLocation storeLocation)
   at My.Api.Startup.ConfigureServices(IServiceCollection services) in D:\temelj\My.FabricApp\src\My.Api\Startup.cs:line 97
```

#### Service Fabric Runtime and SDK Version :
Runtime: 7.0.466.9590
SDK: 4.0.466.9590
.NET Core 3.1

**Comment by temelj** [comment]
The issue is Organic!

I have verified that the EncryptionUtility does indeed work when the service fabric app is executed under my personal domain account.

However when you change it to a AD/service_account then Decryption does not work since it cannot locate the certificate with the above mentioned thumbprint.

In translation :
The certificate needs to be configured for the Fabric App via the ApplicatonManifest.xml
And then a proper loading of the secrets into application configuration.

SEE: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-secret-management

Please note when adding the SF Configuration

```
                                    .AddServiceFabricConfiguration(serviceContext.CodePackageActivationContext, (options)=>{
    options.IncludePackageName = false;
    options.DecryptValue = true;
})
```

And another nice thing to have is mapping the configuration to IOptions<> for DI
```
services.Configure<AuthProviderApiOptions>(Configuration.GetSection("AuthProviderApi"));
```
